#ifndef __GLOBAL_CONST_H__
#define __GLOBAL_CONST_H__

//最小在线人数 MIN_GATEHOME_GROUP_NUM*GATEHOME_GROUP_NUM 10000
#define MIN_GATEHOME_GROUP_NUM  2
#define GATEHOME_GROUP_NUM		5000
#define GATEHOME_PIECE_NUM		1000

#endif //__GLOBAL_CONST_H__
