// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_iid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace com.cms.client.network.gpro {

  /// <summary>Holder for reflection information generated from proto_iid.proto</summary>
  public static partial class ProtoIidReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_iid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoIidReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wcm90b19paWQucHJvdG8SA1BSTyr8AgoMVVNFUl9QUk9UWVBFEhIKDlVO",
            "SVZFUlNBTF8zMDAwEAASEQoMRVJLX1VTRVJfTlVNELgXEhMKDlVTRVJfTE9H",
            "SU5fUkVRELkXEhMKDlVTRVJfTE9HSU5fQUNLELoXEhgKE1VTRVJfUFJPWFlM",
            "T0dJTl9SRVEQuxcSGAoTVVNFUl9QUk9YWUxPR0lOX0FDSxC8FxIUCg9VU0VS",
            "X0xPR09VVF9OVEYQvRcSFgoRVVNFUl9ST0xFTElTVF9BQ0sQvxcSGAoTVVNF",
            "Ul9ST0xFU0VMRUNUX1JFURDAFxIYChNVU0VSX1JPTEVTRUxFQ1RfQUNLEMEX",
            "EhgKE1VTRVJfUk9MRUNSRUFURV9SRVEQwhcSGAoTVVNFUl9ST0xFQ1JFQVRF",
            "X0FDSxDDFxIZChRVU0VSX1JPTEVERVRBSUxBX05URhDEFxIZChRVU0VSX1JP",
            "TEVERVRBSUxCX05URhDFFxIbChZVU0VSX1JPTEVERVRBSUxFTkRfTlRGEMYX",
            "KoMBCg1CVUlMRF9QUk9UWVBFEhIKDlVOSVZFUlNBTF8zNTAwEAASFgoRQlVJ",
            "TERfQURESVRFTV9SRVEQrRsSFgoRQlVJTERfQURESVRFTV9BQ0sQrhsSFgoR",
            "QlVJTERfREVMSVRFTV9SRVEQrxsSFgoRQlVJTERfREVMSVRFTV9BQ0sQsBsq",
            "gQEKC1BFVF9QUk9UWVBFEhIKDlVOSVZFUlNBTF80MDAwEAASFQoQUEVUX0FE",
            "T1BUT05FX1JFURChHxIVChBQRVRfQURPUFRPTkVfQUNLEKIfEhcKElBFVF9S",
            "RUxFQVNFT05FX1JFURCjHxIXChJQRVRfUkVMRUFTRU9ORV9BQ0sQpB8q7gEK",
            "DENIQVRfUFJPVFlQRRISCg5VTklWRVJTQUxfNDUwMBAAEhMKDkNIQVRfTVNH",
            "X0JFR0lOEJQjEhcKEkNIQVRfR0xPQkFMTVNHX05URhCVIxIdChhDSEFUX1VT",
            "RVJDSEFOTkVMU19BQ1RJVkUQniMSHQoYQ0hBVF9DVVNUT01DSEFOTkVMSURf",
            "UkVREKMjEh0KGENIQVRfQ1VTVE9NQ0hBTk5FTElEX0FDSxCkIxIVChBDSEFU",
            "X1VTRVJNU0dfU0FZEKgjEhUKEENIQVRfQ0hBVE1TR19OVEYQqSMSEQoMQ0hB",
            "VF9NU0dfRU5EEMAlKtwDCgxNQUlMX1BST1RZUEUSEgoOVU5JVkVSU0FMXzUw",
            "MDAQABITCg5NQUlMX01TR19CRUdJThCIJxIVChBNQUlMX05FV01BSUxfTlRG",
            "EIknEhUKEE1BSUxfTUFJTEdFVF9SRVEQiicSFQoQTUFJTF9NQUlMR0VUX0FD",
            "SxCLJxIbChZNQUlMX1VTRVJPTkxJTkVfQUNUSVZFEIwnEhYKEU1BSUxfUkVB",
            "RE1BSUxfUkVREI0nEhYKEU1BSUxfUkVBRE1BSUxfQUNLEI4nEhgKE01BSUxf",
            "REVMRVRFTUFJTF9SRVEQjycSGAoTTUFJTF9ERUxFVEVNQUlMX0FDSxCQJxIb",
            "ChZNQUlMX1VOQklOREFUVEFDSFNfUkVREJEnEhsKFk1BSUxfVU5CSU5EQVRU",
            "QUNIU19BQ0sQkicSGAoTTUFJTF9TWVNURU1NQUlMX1JFURDRKBIYChNNQUlM",
            "X1NZU1RFTU1BSUxfQUNLENIoEhgKE01BSUxfU1lTVEVNTUFJTF9OVEYQ0ygS",
            "FQoQTUFJTF9ORVdNQUlMX1JFURDUKBIVChBNQUlMX05FV01BSUxfQUNLENUo",
            "EhEKDE1BSUxfTVNHX0VORBD4KBIUCg9NQUlMX01TR0FMTF9FTkQQgSkq3gIK",
            "DkZSSUVORF9QUk9UWVBFEhIKDlVOSVZFUlNBTF81MjUwEAASFQoQRlJJRU5E",
            "X01TR19CRUdJThCCKRIXChJGUkRfRlJJRU5ETElTVF9SRVEQgykSFwoSRlJE",
            "X0ZSSUVORExJU1RfQUNLEIQpEhkKFEZSRF9GUklFTkRJTlZJVEVfUkVREIUp",
            "EhkKFEZSRF9GUklFTkRJTlZJVEVfQUNLEIYpEhoKFUZSRF9JTlZJVEVDT05G",
            "SVJNX1JFURCHKRIaChVGUkRfSU5WSVRFQ09ORklSTV9BQ0sQiCkSGQoURlJE",
            "X0ZSSUVORERFTEVURV9SRVEQiSkSGQoURlJEX0ZSSUVORERFTEVURV9BQ0sQ",
            "iikSEwoORlJJRU5EX01TR19FTkQQmCoSHgoZRlJEX0ZSSUVORENIQU5HRU9U",
            "SEVSX05URhCZKhIWChFGUklFTkRfTVNHQUxMX0VORBDJKipdCg1JVEVNU19Q",
            "Uk9UWVBFEhIKDlVOSVZFUlNBTF81NTAwEAASGwoWSVRFTV9VU0VSQklORElU",
            "RU1TX1JFURD9KhIbChZJVEVNX1VTRVJCSU5ESVRFTVNfQUNLEP4qQlQKG2Nv",
            "bS5jbXMuY2xpZW50Lm5ldHdvcmsuZ3Byb1ABWhVnYW1lbGliL3Byb3RvYnVm",
            "L2dwcm+qAhtjb20uY21zLmNsaWVudC5uZXR3b3JrLmdwcm9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::com.cms.client.network.gpro.USER_PROTYPE), typeof(global::com.cms.client.network.gpro.BUILD_PROTYPE), typeof(global::com.cms.client.network.gpro.PET_PROTYPE), typeof(global::com.cms.client.network.gpro.CHAT_PROTYPE), typeof(global::com.cms.client.network.gpro.MAIL_PROTYPE), typeof(global::com.cms.client.network.gpro.FRIEND_PROTYPE), typeof(global::com.cms.client.network.gpro.ITEMS_PROTYPE), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///用户定义的协议
  /// </summary>
  public enum USER_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_3000")] Universal3000 = 0,
    [pbr::OriginalName("ERK_USER_NUM")] ErkUserNum = 3000,
    /// <summary>
    ///用户协议
    /// </summary>
    [pbr::OriginalName("USER_LOGIN_REQ")] UserLoginReq = 3001,
    [pbr::OriginalName("USER_LOGIN_ACK")] UserLoginAck = 3002,
    [pbr::OriginalName("USER_PROXYLOGIN_REQ")] UserProxyloginReq = 3003,
    [pbr::OriginalName("USER_PROXYLOGIN_ACK")] UserProxyloginAck = 3004,
    [pbr::OriginalName("USER_LOGOUT_NTF")] UserLogoutNtf = 3005,
    [pbr::OriginalName("USER_ROLELIST_ACK")] UserRolelistAck = 3007,
    [pbr::OriginalName("USER_ROLESELECT_REQ")] UserRoleselectReq = 3008,
    [pbr::OriginalName("USER_ROLESELECT_ACK")] UserRoleselectAck = 3009,
    [pbr::OriginalName("USER_ROLECREATE_REQ")] UserRolecreateReq = 3010,
    [pbr::OriginalName("USER_ROLECREATE_ACK")] UserRolecreateAck = 3011,
    [pbr::OriginalName("USER_ROLEDETAILA_NTF")] UserRoledetailaNtf = 3012,
    [pbr::OriginalName("USER_ROLEDETAILB_NTF")] UserRoledetailbNtf = 3013,
    [pbr::OriginalName("USER_ROLEDETAILEND_NTF")] UserRoledetailendNtf = 3014,
  }

  public enum BUILD_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_3500")] Universal3500 = 0,
    [pbr::OriginalName("BUILD_ADDITEM_REQ")] BuildAdditemReq = 3501,
    [pbr::OriginalName("BUILD_ADDITEM_ACK")] BuildAdditemAck = 3502,
    [pbr::OriginalName("BUILD_DELITEM_REQ")] BuildDelitemReq = 3503,
    [pbr::OriginalName("BUILD_DELITEM_ACK")] BuildDelitemAck = 3504,
  }

  public enum PET_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_4000")] Universal4000 = 0,
    [pbr::OriginalName("PET_ADOPTONE_REQ")] PetAdoptoneReq = 4001,
    [pbr::OriginalName("PET_ADOPTONE_ACK")] PetAdoptoneAck = 4002,
    [pbr::OriginalName("PET_RELEASEONE_REQ")] PetReleaseoneReq = 4003,
    [pbr::OriginalName("PET_RELEASEONE_ACK")] PetReleaseoneAck = 4004,
  }

  public enum CHAT_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_4500")] Universal4500 = 0,
    [pbr::OriginalName("CHAT_MSG_BEGIN")] ChatMsgBegin = 4500,
    [pbr::OriginalName("CHAT_GLOBALMSG_NTF")] ChatGlobalmsgNtf = 4501,
    [pbr::OriginalName("CHAT_USERCHANNELS_ACTIVE")] ChatUserchannelsActive = 4510,
    [pbr::OriginalName("CHAT_CUSTOMCHANNELID_REQ")] ChatCustomchannelidReq = 4515,
    [pbr::OriginalName("CHAT_CUSTOMCHANNELID_ACK")] ChatCustomchannelidAck = 4516,
    [pbr::OriginalName("CHAT_USERMSG_SAY")] ChatUsermsgSay = 4520,
    [pbr::OriginalName("CHAT_CHATMSG_NTF")] ChatChatmsgNtf = 4521,
    [pbr::OriginalName("CHAT_MSG_END")] ChatMsgEnd = 4800,
  }

  public enum MAIL_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_5000")] Universal5000 = 0,
    [pbr::OriginalName("MAIL_MSG_BEGIN")] MailMsgBegin = 5000,
    [pbr::OriginalName("MAIL_NEWMAIL_NTF")] MailNewmailNtf = 5001,
    [pbr::OriginalName("MAIL_MAILGET_REQ")] MailMailgetReq = 5002,
    [pbr::OriginalName("MAIL_MAILGET_ACK")] MailMailgetAck = 5003,
    [pbr::OriginalName("MAIL_USERONLINE_ACTIVE")] MailUseronlineActive = 5004,
    [pbr::OriginalName("MAIL_READMAIL_REQ")] MailReadmailReq = 5005,
    [pbr::OriginalName("MAIL_READMAIL_ACK")] MailReadmailAck = 5006,
    [pbr::OriginalName("MAIL_DELETEMAIL_REQ")] MailDeletemailReq = 5007,
    [pbr::OriginalName("MAIL_DELETEMAIL_ACK")] MailDeletemailAck = 5008,
    [pbr::OriginalName("MAIL_UNBINDATTACHS_REQ")] MailUnbindattachsReq = 5009,
    [pbr::OriginalName("MAIL_UNBINDATTACHS_ACK")] MailUnbindattachsAck = 5010,
    [pbr::OriginalName("MAIL_SYSTEMMAIL_REQ")] MailSystemmailReq = 5201,
    [pbr::OriginalName("MAIL_SYSTEMMAIL_ACK")] MailSystemmailAck = 5202,
    [pbr::OriginalName("MAIL_SYSTEMMAIL_NTF")] MailSystemmailNtf = 5203,
    [pbr::OriginalName("MAIL_NEWMAIL_REQ")] MailNewmailReq = 5204,
    [pbr::OriginalName("MAIL_NEWMAIL_ACK")] MailNewmailAck = 5205,
    [pbr::OriginalName("MAIL_MSG_END")] MailMsgEnd = 5240,
    [pbr::OriginalName("MAIL_MSGALL_END")] MailMsgallEnd = 5249,
  }

  public enum FRIEND_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_5250")] Universal5250 = 0,
    [pbr::OriginalName("FRIEND_MSG_BEGIN")] FriendMsgBegin = 5250,
    [pbr::OriginalName("FRD_FRIENDLIST_REQ")] FrdFriendlistReq = 5251,
    [pbr::OriginalName("FRD_FRIENDLIST_ACK")] FrdFriendlistAck = 5252,
    [pbr::OriginalName("FRD_FRIENDINVITE_REQ")] FrdFriendinviteReq = 5253,
    [pbr::OriginalName("FRD_FRIENDINVITE_ACK")] FrdFriendinviteAck = 5254,
    [pbr::OriginalName("FRD_INVITECONFIRM_REQ")] FrdInviteconfirmReq = 5255,
    [pbr::OriginalName("FRD_INVITECONFIRM_ACK")] FrdInviteconfirmAck = 5256,
    [pbr::OriginalName("FRD_FRIENDDELETE_REQ")] FrdFrienddeleteReq = 5257,
    [pbr::OriginalName("FRD_FRIENDDELETE_ACK")] FrdFrienddeleteAck = 5258,
    [pbr::OriginalName("FRIEND_MSG_END")] FriendMsgEnd = 5400,
    [pbr::OriginalName("FRD_FRIENDCHANGEOTHER_NTF")] FrdFriendchangeotherNtf = 5401,
    [pbr::OriginalName("FRIEND_MSGALL_END")] FriendMsgallEnd = 5449,
  }

  public enum ITEMS_PROTYPE {
    [pbr::OriginalName("UNIVERSAL_5500")] Universal5500 = 0,
    [pbr::OriginalName("ITEM_USERBINDITEMS_REQ")] ItemUserbinditemsReq = 5501,
    [pbr::OriginalName("ITEM_USERBINDITEMS_ACK")] ItemUserbinditemsAck = 5502,
  }

  #endregion

}

#endregion Designer generated code
