// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_internal.proto

package com.cms.client.network.gpro;

public final class DbInternal {
  private DbInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBRowDel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBRowDel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBRowDeletes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBRowDeletes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBRoleBaseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBRoleBaseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserRoles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserRoles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserHome_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserHome_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserHomeStructureItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserHomeStructureItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserHomeStructure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserHomeStructure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBPetCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBPetCategory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserPetItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserPetItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserPets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserPets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBTaskAttrData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBTaskAttrData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBTaskAttrData_DatasEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBTaskAttrData_DatasEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTasks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTasks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskEndItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskEndItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskEnds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskEnds_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBTaskGAttrData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBTaskGAttrData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBTaskGAttrData_DatasEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBTaskGAttrData_DatasEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskGroups_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskGroups_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskGroupEnd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskGroupEnd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserTaskGroupEnds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserTaskGroupEnds_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserBattleInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserBattleInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_DBUserBattles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_DBUserBattles_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021db_internal.proto\022\003PRO\"$\n\010DBRowDel\022\014\n\004" +
      "ver_\030\001 \001(\r\022\n\n\002id\030\002 \001(\003\"+\n\014DBRowDeletes\022\033" +
      "\n\004dels\030\001 \003(\0132\r.PRO.DBRowDel\"w\n\016DBRoleBas" +
      "eInfo\022\014\n\004ver_\030\001 \001(\r\022\020\n\010role_iid\030\002 \001(\003\022\020\n" +
      "\010user_iid\030\003 \001(\003\022\020\n\010nickname\030\004 \001(\t\022\021\n\treg" +
      "istime\030\005 \001(\005\022\016\n\006levels\030\006 \001(\005\"1\n\013DBUserRo" +
      "les\022\"\n\005roles\030\001 \003(\0132\023.PRO.DBRoleBaseInfo\"" +
      "\265\001\n\nDBUserHome\022\014\n\004ver_\030\001 \001(\r\022\020\n\010role_iid" +
      "\030\002 \001(\003\022\021\n\thome_name\030\003 \001(\t\022\024\n\014ground_resi" +
      "d\030\004 \001(\003\022\017\n\007look_at\030\005 \001(\t\022\017\n\007geo_pos\030\006 \001(" +
      "\t\022\023\n\013reside_time\030\007 \001(\005\022\027\n\017last_residedat" +
      "e\030\010 \001(\005\022\016\n\006levels\030\t \001(\005\"\267\001\n\027DBUserHomeSt" +
      "ructureItem\022\014\n\004ver_\030\001 \001(\r\022\024\n\014building_ii" +
      "d\030\002 \001(\003\022\020\n\010home_iid\030\003 \001(\003\022\027\n\017parent_buil" +
      "ding\030\004 \001(\003\022\026\n\016building_resid\030\005 \001(\003\022\017\n\007lo" +
      "ok_at\030\006 \001(\t\022\024\n\014building_pos\030\007 \001(\t\022\016\n\006lev" +
      "els\030\010 \001(\005\"B\n\023DBUserHomeStructure\022+\n\005item" +
      "s\030\001 \003(\0132\034.PRO.DBUserHomeStructureItem\"h\n" +
      "\rDBPetCategory\022\017\n\007pet_iid\030\002 \001(\003\022\020\n\010pet_t" +
      "ype\030\003 \001(\005\022\021\n\tpet_resid\030\004 \001(\003\022\017\n\007pet_sex\030" +
      "\005 \001(\005\022\020\n\010pet_name\030\006 \001(\t\"v\n\rDBUserPetItem" +
      "\022\014\n\004ver_\030\001 \001(\r\022\021\n\tmypet_iid\030\002 \001(\003\022\020\n\010rol" +
      "e_iid\030\003 \001(\003\022\017\n\007pet_iid\030\004 \001(\003\022\017\n\007pet_age\030" +
      "\005 \001(\005\022\020\n\010birthday\030\006 \001(\005\".\n\nDBUserPets\022 \n" +
      "\004pets\030\001 \003(\0132\022.PRO.DBUserPetItem\"m\n\016DBTas" +
      "kAttrData\022-\n\005datas\030\001 \003(\0132\036.PRO.DBTaskAtt" +
      "rData.DatasEntry\032,\n\nDatasEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\003:\0028\001\"\310\002\n\016DBUserTaskIte" +
      "m\022\014\n\004ver_\030\001 \001(\r\022\013\n\003iid\030\002 \001(\003\022\020\n\010role_iid" +
      "\030\003 \001(\003\022\020\n\010task_iid\030\004 \001(\005\022\024\n\014my_taskgroup" +
      "\030\005 \001(\003\022\022\n\ntask_group\030\006 \001(\005\022\016\n\006qstate\030\007 \001" +
      "(\005\022\024\n\014accept_level\030\010 \001(\005\022\022\n\ncycle_task\030\t" +
      " \001(\010\022\021\n\tcycle_num\030\n \001(\005\022\022\n\ncreatetime\030\013 " +
      "\001(\005\022\027\n\017firstupdatetime\030\014 \001(\005\022\026\n\016lastupda" +
      "tetime\030\r \001(\005\022\'\n\ntask_datas\030\016 \001(\0132\023.PRO.D" +
      "BTaskAttrData\022\022\n\nsource_iid\030\017 \001(\t\"1\n\013DBU" +
      "serTasks\022\"\n\005items\030\001 \003(\0132\023.PRO.DBUserTask" +
      "Item\"h\n\021DBUserTaskEndItem\022\014\n\004ver_\030\001 \001(\r\022" +
      "\013\n\003iid\030\002 \001(\003\022\020\n\010task_iid\030\004 \001(\005\022\016\n\006qstate" +
      "\030\007 \001(\005\022\026\n\016lastupdatetime\030\r \001(\005\"7\n\016DBUser" +
      "TaskEnds\022%\n\005items\030\001 \003(\0132\026.PRO.DBUserTask" +
      "EndItem\"o\n\017DBTaskGAttrData\022.\n\005datas\030\001 \003(" +
      "\0132\037.PRO.DBTaskGAttrData.DatasEntry\032,\n\nDa" +
      "tasEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001" +
      "\"\331\001\n\017DBUserTaskGroup\022\014\n\004ver_\030\001 \001(\r\022\013\n\003ii" +
      "d\030\002 \001(\003\022\020\n\010role_iid\030\003 \001(\003\022\022\n\ntask_group\030" +
      "\004 \001(\005\022\022\n\ngroup_cell\030\005 \001(\005\022\'\n\tcell_data\030\006" +
      " \001(\0132\024.PRO.DBTaskGAttrData\022\016\n\006gstate\030\007 \001" +
      "(\005\022\023\n\013trigg_level\030\010 \001(\005\022\022\n\ncreatetime\030\t " +
      "\001(\005\022\017\n\007endtime\030\n \001(\005\"8\n\020DBUserTaskGroups" +
      "\022$\n\006groups\030\001 \003(\0132\024.PRO.DBUserTaskGroup\"d" +
      "\n\022DBUserTaskGroupEnd\022\014\n\004ver_\030\001 \001(\r\022\013\n\003ii" +
      "d\030\002 \001(\003\022\022\n\ntask_group\030\004 \001(\005\022\016\n\006gstate\030\007 " +
      "\001(\005\022\017\n\007endtime\030\n \001(\005\">\n\023DBUserTaskGroupE" +
      "nds\022\'\n\006groups\030\001 \003(\0132\027.PRO.DBUserTaskGrou" +
      "pEnd\"~\n\020DBUserBattleInfo\022\014\n\004ver_\030\001 \001(\r\022\013" +
      "\n\003iid\030\002 \001(\003\022\020\n\010role_iid\030\003 \001(\003\022\016\n\006levels\030" +
      "\004 \001(\005\022\017\n\007victory\030\005 \001(\005\022\016\n\006defeat\030\006 \001(\005\022\014" +
      "\n\004draw\030\007 \001(\005\"5\n\rDBUserBattles\022$\n\005infos\030\001" +
      " \003(\0132\025.PRO.DBUserBattleInfoBT\n\033com.cms.c" +
      "lient.network.gproP\001Z\025gamelib/protobuf/g" +
      "pro\252\002\033com.cms.client.network.gprob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PRO_DBRowDel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PRO_DBRowDel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBRowDel_descriptor,
        new java.lang.String[] { "Ver", "Id", });
    internal_static_PRO_DBRowDeletes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PRO_DBRowDeletes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBRowDeletes_descriptor,
        new java.lang.String[] { "Dels", });
    internal_static_PRO_DBRoleBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PRO_DBRoleBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBRoleBaseInfo_descriptor,
        new java.lang.String[] { "Ver", "RoleIid", "UserIid", "Nickname", "Registime", "Levels", });
    internal_static_PRO_DBUserRoles_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PRO_DBUserRoles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserRoles_descriptor,
        new java.lang.String[] { "Roles", });
    internal_static_PRO_DBUserHome_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PRO_DBUserHome_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserHome_descriptor,
        new java.lang.String[] { "Ver", "RoleIid", "HomeName", "GroundResid", "LookAt", "GeoPos", "ResideTime", "LastResidedate", "Levels", });
    internal_static_PRO_DBUserHomeStructureItem_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PRO_DBUserHomeStructureItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserHomeStructureItem_descriptor,
        new java.lang.String[] { "Ver", "BuildingIid", "HomeIid", "ParentBuilding", "BuildingResid", "LookAt", "BuildingPos", "Levels", });
    internal_static_PRO_DBUserHomeStructure_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_PRO_DBUserHomeStructure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserHomeStructure_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_PRO_DBPetCategory_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_PRO_DBPetCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBPetCategory_descriptor,
        new java.lang.String[] { "PetIid", "PetType", "PetResid", "PetSex", "PetName", });
    internal_static_PRO_DBUserPetItem_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_PRO_DBUserPetItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserPetItem_descriptor,
        new java.lang.String[] { "Ver", "MypetIid", "RoleIid", "PetIid", "PetAge", "Birthday", });
    internal_static_PRO_DBUserPets_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_PRO_DBUserPets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserPets_descriptor,
        new java.lang.String[] { "Pets", });
    internal_static_PRO_DBTaskAttrData_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_PRO_DBTaskAttrData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBTaskAttrData_descriptor,
        new java.lang.String[] { "Datas", });
    internal_static_PRO_DBTaskAttrData_DatasEntry_descriptor =
      internal_static_PRO_DBTaskAttrData_descriptor.getNestedTypes().get(0);
    internal_static_PRO_DBTaskAttrData_DatasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBTaskAttrData_DatasEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PRO_DBUserTaskItem_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_PRO_DBUserTaskItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskItem_descriptor,
        new java.lang.String[] { "Ver", "Iid", "RoleIid", "TaskIid", "MyTaskgroup", "TaskGroup", "Qstate", "AcceptLevel", "CycleTask", "CycleNum", "Createtime", "Firstupdatetime", "Lastupdatetime", "TaskDatas", "SourceIid", });
    internal_static_PRO_DBUserTasks_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_PRO_DBUserTasks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTasks_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_PRO_DBUserTaskEndItem_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_PRO_DBUserTaskEndItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskEndItem_descriptor,
        new java.lang.String[] { "Ver", "Iid", "TaskIid", "Qstate", "Lastupdatetime", });
    internal_static_PRO_DBUserTaskEnds_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_PRO_DBUserTaskEnds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskEnds_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_PRO_DBTaskGAttrData_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_PRO_DBTaskGAttrData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBTaskGAttrData_descriptor,
        new java.lang.String[] { "Datas", });
    internal_static_PRO_DBTaskGAttrData_DatasEntry_descriptor =
      internal_static_PRO_DBTaskGAttrData_descriptor.getNestedTypes().get(0);
    internal_static_PRO_DBTaskGAttrData_DatasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBTaskGAttrData_DatasEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PRO_DBUserTaskGroup_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_PRO_DBUserTaskGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskGroup_descriptor,
        new java.lang.String[] { "Ver", "Iid", "RoleIid", "TaskGroup", "GroupCell", "CellData", "Gstate", "TriggLevel", "Createtime", "Endtime", });
    internal_static_PRO_DBUserTaskGroups_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_PRO_DBUserTaskGroups_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskGroups_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_PRO_DBUserTaskGroupEnd_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_PRO_DBUserTaskGroupEnd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskGroupEnd_descriptor,
        new java.lang.String[] { "Ver", "Iid", "TaskGroup", "Gstate", "Endtime", });
    internal_static_PRO_DBUserTaskGroupEnds_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_PRO_DBUserTaskGroupEnds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserTaskGroupEnds_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_PRO_DBUserBattleInfo_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_PRO_DBUserBattleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserBattleInfo_descriptor,
        new java.lang.String[] { "Ver", "Iid", "RoleIid", "Levels", "Victory", "Defeat", "Draw", });
    internal_static_PRO_DBUserBattles_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_PRO_DBUserBattles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_DBUserBattles_descriptor,
        new java.lang.String[] { "Infos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
