// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_internal.proto

package com.cms.client.network.gpro;

/**
 * Protobuf type {@code PRO.DBUserTaskItem}
 */
public final class DBUserTaskItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PRO.DBUserTaskItem)
    DBUserTaskItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DBUserTaskItem.newBuilder() to construct.
  private DBUserTaskItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DBUserTaskItem() {
    sourceIid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DBUserTaskItem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DBUserTaskItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ver_ = input.readUInt32();
            break;
          }
          case 16: {

            iid_ = input.readInt64();
            break;
          }
          case 24: {

            roleIid_ = input.readInt64();
            break;
          }
          case 32: {

            taskIid_ = input.readInt32();
            break;
          }
          case 40: {

            myTaskgroup_ = input.readInt64();
            break;
          }
          case 48: {

            taskGroup_ = input.readInt32();
            break;
          }
          case 56: {

            qstate_ = input.readInt32();
            break;
          }
          case 64: {

            acceptLevel_ = input.readInt32();
            break;
          }
          case 72: {

            cycleTask_ = input.readBool();
            break;
          }
          case 80: {

            cycleNum_ = input.readInt32();
            break;
          }
          case 88: {

            createtime_ = input.readInt32();
            break;
          }
          case 96: {

            firstupdatetime_ = input.readInt32();
            break;
          }
          case 104: {

            lastupdatetime_ = input.readInt32();
            break;
          }
          case 114: {
            com.cms.client.network.gpro.DBTaskAttrData.Builder subBuilder = null;
            if (taskDatas_ != null) {
              subBuilder = taskDatas_.toBuilder();
            }
            taskDatas_ = input.readMessage(com.cms.client.network.gpro.DBTaskAttrData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(taskDatas_);
              taskDatas_ = subBuilder.buildPartial();
            }

            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceIid_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cms.client.network.gpro.DbInternal.internal_static_PRO_DBUserTaskItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cms.client.network.gpro.DbInternal.internal_static_PRO_DBUserTaskItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cms.client.network.gpro.DBUserTaskItem.class, com.cms.client.network.gpro.DBUserTaskItem.Builder.class);
  }

  public static final int VER__FIELD_NUMBER = 1;
  private int ver_;
  /**
   * <code>uint32 ver_ = 1;</code>
   * @return The ver.
   */
  @java.lang.Override
  public int getVer() {
    return ver_;
  }

  public static final int IID_FIELD_NUMBER = 2;
  private long iid_;
  /**
   * <code>int64 iid = 2;</code>
   * @return The iid.
   */
  @java.lang.Override
  public long getIid() {
    return iid_;
  }

  public static final int ROLE_IID_FIELD_NUMBER = 3;
  private long roleIid_;
  /**
   * <code>int64 role_iid = 3;</code>
   * @return The roleIid.
   */
  @java.lang.Override
  public long getRoleIid() {
    return roleIid_;
  }

  public static final int TASK_IID_FIELD_NUMBER = 4;
  private int taskIid_;
  /**
   * <code>int32 task_iid = 4;</code>
   * @return The taskIid.
   */
  @java.lang.Override
  public int getTaskIid() {
    return taskIid_;
  }

  public static final int MY_TASKGROUP_FIELD_NUMBER = 5;
  private long myTaskgroup_;
  /**
   * <code>int64 my_taskgroup = 5;</code>
   * @return The myTaskgroup.
   */
  @java.lang.Override
  public long getMyTaskgroup() {
    return myTaskgroup_;
  }

  public static final int TASK_GROUP_FIELD_NUMBER = 6;
  private int taskGroup_;
  /**
   * <code>int32 task_group = 6;</code>
   * @return The taskGroup.
   */
  @java.lang.Override
  public int getTaskGroup() {
    return taskGroup_;
  }

  public static final int QSTATE_FIELD_NUMBER = 7;
  private int qstate_;
  /**
   * <code>int32 qstate = 7;</code>
   * @return The qstate.
   */
  @java.lang.Override
  public int getQstate() {
    return qstate_;
  }

  public static final int ACCEPT_LEVEL_FIELD_NUMBER = 8;
  private int acceptLevel_;
  /**
   * <code>int32 accept_level = 8;</code>
   * @return The acceptLevel.
   */
  @java.lang.Override
  public int getAcceptLevel() {
    return acceptLevel_;
  }

  public static final int CYCLE_TASK_FIELD_NUMBER = 9;
  private boolean cycleTask_;
  /**
   * <code>bool cycle_task = 9;</code>
   * @return The cycleTask.
   */
  @java.lang.Override
  public boolean getCycleTask() {
    return cycleTask_;
  }

  public static final int CYCLE_NUM_FIELD_NUMBER = 10;
  private int cycleNum_;
  /**
   * <code>int32 cycle_num = 10;</code>
   * @return The cycleNum.
   */
  @java.lang.Override
  public int getCycleNum() {
    return cycleNum_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 11;
  private int createtime_;
  /**
   * <code>int32 createtime = 11;</code>
   * @return The createtime.
   */
  @java.lang.Override
  public int getCreatetime() {
    return createtime_;
  }

  public static final int FIRSTUPDATETIME_FIELD_NUMBER = 12;
  private int firstupdatetime_;
  /**
   * <code>int32 firstupdatetime = 12;</code>
   * @return The firstupdatetime.
   */
  @java.lang.Override
  public int getFirstupdatetime() {
    return firstupdatetime_;
  }

  public static final int LASTUPDATETIME_FIELD_NUMBER = 13;
  private int lastupdatetime_;
  /**
   * <code>int32 lastupdatetime = 13;</code>
   * @return The lastupdatetime.
   */
  @java.lang.Override
  public int getLastupdatetime() {
    return lastupdatetime_;
  }

  public static final int TASK_DATAS_FIELD_NUMBER = 14;
  private com.cms.client.network.gpro.DBTaskAttrData taskDatas_;
  /**
   * <pre>
   *string task_datas = 14;
   * </pre>
   *
   * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
   * @return Whether the taskDatas field is set.
   */
  @java.lang.Override
  public boolean hasTaskDatas() {
    return taskDatas_ != null;
  }
  /**
   * <pre>
   *string task_datas = 14;
   * </pre>
   *
   * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
   * @return The taskDatas.
   */
  @java.lang.Override
  public com.cms.client.network.gpro.DBTaskAttrData getTaskDatas() {
    return taskDatas_ == null ? com.cms.client.network.gpro.DBTaskAttrData.getDefaultInstance() : taskDatas_;
  }
  /**
   * <pre>
   *string task_datas = 14;
   * </pre>
   *
   * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
   */
  @java.lang.Override
  public com.cms.client.network.gpro.DBTaskAttrDataOrBuilder getTaskDatasOrBuilder() {
    return getTaskDatas();
  }

  public static final int SOURCE_IID_FIELD_NUMBER = 15;
  private volatile java.lang.Object sourceIid_;
  /**
   * <code>string source_iid = 15;</code>
   * @return The sourceIid.
   */
  @java.lang.Override
  public java.lang.String getSourceIid() {
    java.lang.Object ref = sourceIid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceIid_ = s;
      return s;
    }
  }
  /**
   * <code>string source_iid = 15;</code>
   * @return The bytes for sourceIid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIidBytes() {
    java.lang.Object ref = sourceIid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceIid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ver_ != 0) {
      output.writeUInt32(1, ver_);
    }
    if (iid_ != 0L) {
      output.writeInt64(2, iid_);
    }
    if (roleIid_ != 0L) {
      output.writeInt64(3, roleIid_);
    }
    if (taskIid_ != 0) {
      output.writeInt32(4, taskIid_);
    }
    if (myTaskgroup_ != 0L) {
      output.writeInt64(5, myTaskgroup_);
    }
    if (taskGroup_ != 0) {
      output.writeInt32(6, taskGroup_);
    }
    if (qstate_ != 0) {
      output.writeInt32(7, qstate_);
    }
    if (acceptLevel_ != 0) {
      output.writeInt32(8, acceptLevel_);
    }
    if (cycleTask_ != false) {
      output.writeBool(9, cycleTask_);
    }
    if (cycleNum_ != 0) {
      output.writeInt32(10, cycleNum_);
    }
    if (createtime_ != 0) {
      output.writeInt32(11, createtime_);
    }
    if (firstupdatetime_ != 0) {
      output.writeInt32(12, firstupdatetime_);
    }
    if (lastupdatetime_ != 0) {
      output.writeInt32(13, lastupdatetime_);
    }
    if (taskDatas_ != null) {
      output.writeMessage(14, getTaskDatas());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceIid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, sourceIid_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ver_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, ver_);
    }
    if (iid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, iid_);
    }
    if (roleIid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, roleIid_);
    }
    if (taskIid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, taskIid_);
    }
    if (myTaskgroup_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, myTaskgroup_);
    }
    if (taskGroup_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, taskGroup_);
    }
    if (qstate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, qstate_);
    }
    if (acceptLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, acceptLevel_);
    }
    if (cycleTask_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, cycleTask_);
    }
    if (cycleNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, cycleNum_);
    }
    if (createtime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, createtime_);
    }
    if (firstupdatetime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, firstupdatetime_);
    }
    if (lastupdatetime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, lastupdatetime_);
    }
    if (taskDatas_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getTaskDatas());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceIid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, sourceIid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cms.client.network.gpro.DBUserTaskItem)) {
      return super.equals(obj);
    }
    com.cms.client.network.gpro.DBUserTaskItem other = (com.cms.client.network.gpro.DBUserTaskItem) obj;

    if (getVer()
        != other.getVer()) return false;
    if (getIid()
        != other.getIid()) return false;
    if (getRoleIid()
        != other.getRoleIid()) return false;
    if (getTaskIid()
        != other.getTaskIid()) return false;
    if (getMyTaskgroup()
        != other.getMyTaskgroup()) return false;
    if (getTaskGroup()
        != other.getTaskGroup()) return false;
    if (getQstate()
        != other.getQstate()) return false;
    if (getAcceptLevel()
        != other.getAcceptLevel()) return false;
    if (getCycleTask()
        != other.getCycleTask()) return false;
    if (getCycleNum()
        != other.getCycleNum()) return false;
    if (getCreatetime()
        != other.getCreatetime()) return false;
    if (getFirstupdatetime()
        != other.getFirstupdatetime()) return false;
    if (getLastupdatetime()
        != other.getLastupdatetime()) return false;
    if (hasTaskDatas() != other.hasTaskDatas()) return false;
    if (hasTaskDatas()) {
      if (!getTaskDatas()
          .equals(other.getTaskDatas())) return false;
    }
    if (!getSourceIid()
        .equals(other.getSourceIid())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VER__FIELD_NUMBER;
    hash = (53 * hash) + getVer();
    hash = (37 * hash) + IID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIid());
    hash = (37 * hash) + ROLE_IID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoleIid());
    hash = (37 * hash) + TASK_IID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskIid();
    hash = (37 * hash) + MY_TASKGROUP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMyTaskgroup());
    hash = (37 * hash) + TASK_GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getTaskGroup();
    hash = (37 * hash) + QSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getQstate();
    hash = (37 * hash) + ACCEPT_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptLevel();
    hash = (37 * hash) + CYCLE_TASK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCycleTask());
    hash = (37 * hash) + CYCLE_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getCycleNum();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreatetime();
    hash = (37 * hash) + FIRSTUPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstupdatetime();
    hash = (37 * hash) + LASTUPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getLastupdatetime();
    if (hasTaskDatas()) {
      hash = (37 * hash) + TASK_DATAS_FIELD_NUMBER;
      hash = (53 * hash) + getTaskDatas().hashCode();
    }
    hash = (37 * hash) + SOURCE_IID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceIid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.DBUserTaskItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cms.client.network.gpro.DBUserTaskItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PRO.DBUserTaskItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PRO.DBUserTaskItem)
      com.cms.client.network.gpro.DBUserTaskItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cms.client.network.gpro.DbInternal.internal_static_PRO_DBUserTaskItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cms.client.network.gpro.DbInternal.internal_static_PRO_DBUserTaskItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cms.client.network.gpro.DBUserTaskItem.class, com.cms.client.network.gpro.DBUserTaskItem.Builder.class);
    }

    // Construct using com.cms.client.network.gpro.DBUserTaskItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ver_ = 0;

      iid_ = 0L;

      roleIid_ = 0L;

      taskIid_ = 0;

      myTaskgroup_ = 0L;

      taskGroup_ = 0;

      qstate_ = 0;

      acceptLevel_ = 0;

      cycleTask_ = false;

      cycleNum_ = 0;

      createtime_ = 0;

      firstupdatetime_ = 0;

      lastupdatetime_ = 0;

      if (taskDatasBuilder_ == null) {
        taskDatas_ = null;
      } else {
        taskDatas_ = null;
        taskDatasBuilder_ = null;
      }
      sourceIid_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cms.client.network.gpro.DbInternal.internal_static_PRO_DBUserTaskItem_descriptor;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.DBUserTaskItem getDefaultInstanceForType() {
      return com.cms.client.network.gpro.DBUserTaskItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.cms.client.network.gpro.DBUserTaskItem build() {
      com.cms.client.network.gpro.DBUserTaskItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.DBUserTaskItem buildPartial() {
      com.cms.client.network.gpro.DBUserTaskItem result = new com.cms.client.network.gpro.DBUserTaskItem(this);
      result.ver_ = ver_;
      result.iid_ = iid_;
      result.roleIid_ = roleIid_;
      result.taskIid_ = taskIid_;
      result.myTaskgroup_ = myTaskgroup_;
      result.taskGroup_ = taskGroup_;
      result.qstate_ = qstate_;
      result.acceptLevel_ = acceptLevel_;
      result.cycleTask_ = cycleTask_;
      result.cycleNum_ = cycleNum_;
      result.createtime_ = createtime_;
      result.firstupdatetime_ = firstupdatetime_;
      result.lastupdatetime_ = lastupdatetime_;
      if (taskDatasBuilder_ == null) {
        result.taskDatas_ = taskDatas_;
      } else {
        result.taskDatas_ = taskDatasBuilder_.build();
      }
      result.sourceIid_ = sourceIid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cms.client.network.gpro.DBUserTaskItem) {
        return mergeFrom((com.cms.client.network.gpro.DBUserTaskItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cms.client.network.gpro.DBUserTaskItem other) {
      if (other == com.cms.client.network.gpro.DBUserTaskItem.getDefaultInstance()) return this;
      if (other.getVer() != 0) {
        setVer(other.getVer());
      }
      if (other.getIid() != 0L) {
        setIid(other.getIid());
      }
      if (other.getRoleIid() != 0L) {
        setRoleIid(other.getRoleIid());
      }
      if (other.getTaskIid() != 0) {
        setTaskIid(other.getTaskIid());
      }
      if (other.getMyTaskgroup() != 0L) {
        setMyTaskgroup(other.getMyTaskgroup());
      }
      if (other.getTaskGroup() != 0) {
        setTaskGroup(other.getTaskGroup());
      }
      if (other.getQstate() != 0) {
        setQstate(other.getQstate());
      }
      if (other.getAcceptLevel() != 0) {
        setAcceptLevel(other.getAcceptLevel());
      }
      if (other.getCycleTask() != false) {
        setCycleTask(other.getCycleTask());
      }
      if (other.getCycleNum() != 0) {
        setCycleNum(other.getCycleNum());
      }
      if (other.getCreatetime() != 0) {
        setCreatetime(other.getCreatetime());
      }
      if (other.getFirstupdatetime() != 0) {
        setFirstupdatetime(other.getFirstupdatetime());
      }
      if (other.getLastupdatetime() != 0) {
        setLastupdatetime(other.getLastupdatetime());
      }
      if (other.hasTaskDatas()) {
        mergeTaskDatas(other.getTaskDatas());
      }
      if (!other.getSourceIid().isEmpty()) {
        sourceIid_ = other.sourceIid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cms.client.network.gpro.DBUserTaskItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cms.client.network.gpro.DBUserTaskItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ver_ ;
    /**
     * <code>uint32 ver_ = 1;</code>
     * @return The ver.
     */
    @java.lang.Override
    public int getVer() {
      return ver_;
    }
    /**
     * <code>uint32 ver_ = 1;</code>
     * @param value The ver to set.
     * @return This builder for chaining.
     */
    public Builder setVer(int value) {
      
      ver_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 ver_ = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVer() {
      
      ver_ = 0;
      onChanged();
      return this;
    }

    private long iid_ ;
    /**
     * <code>int64 iid = 2;</code>
     * @return The iid.
     */
    @java.lang.Override
    public long getIid() {
      return iid_;
    }
    /**
     * <code>int64 iid = 2;</code>
     * @param value The iid to set.
     * @return This builder for chaining.
     */
    public Builder setIid(long value) {
      
      iid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 iid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIid() {
      
      iid_ = 0L;
      onChanged();
      return this;
    }

    private long roleIid_ ;
    /**
     * <code>int64 role_iid = 3;</code>
     * @return The roleIid.
     */
    @java.lang.Override
    public long getRoleIid() {
      return roleIid_;
    }
    /**
     * <code>int64 role_iid = 3;</code>
     * @param value The roleIid to set.
     * @return This builder for chaining.
     */
    public Builder setRoleIid(long value) {
      
      roleIid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 role_iid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoleIid() {
      
      roleIid_ = 0L;
      onChanged();
      return this;
    }

    private int taskIid_ ;
    /**
     * <code>int32 task_iid = 4;</code>
     * @return The taskIid.
     */
    @java.lang.Override
    public int getTaskIid() {
      return taskIid_;
    }
    /**
     * <code>int32 task_iid = 4;</code>
     * @param value The taskIid to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIid(int value) {
      
      taskIid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 task_iid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskIid() {
      
      taskIid_ = 0;
      onChanged();
      return this;
    }

    private long myTaskgroup_ ;
    /**
     * <code>int64 my_taskgroup = 5;</code>
     * @return The myTaskgroup.
     */
    @java.lang.Override
    public long getMyTaskgroup() {
      return myTaskgroup_;
    }
    /**
     * <code>int64 my_taskgroup = 5;</code>
     * @param value The myTaskgroup to set.
     * @return This builder for chaining.
     */
    public Builder setMyTaskgroup(long value) {
      
      myTaskgroup_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 my_taskgroup = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyTaskgroup() {
      
      myTaskgroup_ = 0L;
      onChanged();
      return this;
    }

    private int taskGroup_ ;
    /**
     * <code>int32 task_group = 6;</code>
     * @return The taskGroup.
     */
    @java.lang.Override
    public int getTaskGroup() {
      return taskGroup_;
    }
    /**
     * <code>int32 task_group = 6;</code>
     * @param value The taskGroup to set.
     * @return This builder for chaining.
     */
    public Builder setTaskGroup(int value) {
      
      taskGroup_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 task_group = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskGroup() {
      
      taskGroup_ = 0;
      onChanged();
      return this;
    }

    private int qstate_ ;
    /**
     * <code>int32 qstate = 7;</code>
     * @return The qstate.
     */
    @java.lang.Override
    public int getQstate() {
      return qstate_;
    }
    /**
     * <code>int32 qstate = 7;</code>
     * @param value The qstate to set.
     * @return This builder for chaining.
     */
    public Builder setQstate(int value) {
      
      qstate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 qstate = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearQstate() {
      
      qstate_ = 0;
      onChanged();
      return this;
    }

    private int acceptLevel_ ;
    /**
     * <code>int32 accept_level = 8;</code>
     * @return The acceptLevel.
     */
    @java.lang.Override
    public int getAcceptLevel() {
      return acceptLevel_;
    }
    /**
     * <code>int32 accept_level = 8;</code>
     * @param value The acceptLevel to set.
     * @return This builder for chaining.
     */
    public Builder setAcceptLevel(int value) {
      
      acceptLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 accept_level = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcceptLevel() {
      
      acceptLevel_ = 0;
      onChanged();
      return this;
    }

    private boolean cycleTask_ ;
    /**
     * <code>bool cycle_task = 9;</code>
     * @return The cycleTask.
     */
    @java.lang.Override
    public boolean getCycleTask() {
      return cycleTask_;
    }
    /**
     * <code>bool cycle_task = 9;</code>
     * @param value The cycleTask to set.
     * @return This builder for chaining.
     */
    public Builder setCycleTask(boolean value) {
      
      cycleTask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool cycle_task = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCycleTask() {
      
      cycleTask_ = false;
      onChanged();
      return this;
    }

    private int cycleNum_ ;
    /**
     * <code>int32 cycle_num = 10;</code>
     * @return The cycleNum.
     */
    @java.lang.Override
    public int getCycleNum() {
      return cycleNum_;
    }
    /**
     * <code>int32 cycle_num = 10;</code>
     * @param value The cycleNum to set.
     * @return This builder for chaining.
     */
    public Builder setCycleNum(int value) {
      
      cycleNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cycle_num = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCycleNum() {
      
      cycleNum_ = 0;
      onChanged();
      return this;
    }

    private int createtime_ ;
    /**
     * <code>int32 createtime = 11;</code>
     * @return The createtime.
     */
    @java.lang.Override
    public int getCreatetime() {
      return createtime_;
    }
    /**
     * <code>int32 createtime = 11;</code>
     * @param value The createtime to set.
     * @return This builder for chaining.
     */
    public Builder setCreatetime(int value) {
      
      createtime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 createtime = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatetime() {
      
      createtime_ = 0;
      onChanged();
      return this;
    }

    private int firstupdatetime_ ;
    /**
     * <code>int32 firstupdatetime = 12;</code>
     * @return The firstupdatetime.
     */
    @java.lang.Override
    public int getFirstupdatetime() {
      return firstupdatetime_;
    }
    /**
     * <code>int32 firstupdatetime = 12;</code>
     * @param value The firstupdatetime to set.
     * @return This builder for chaining.
     */
    public Builder setFirstupdatetime(int value) {
      
      firstupdatetime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 firstupdatetime = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstupdatetime() {
      
      firstupdatetime_ = 0;
      onChanged();
      return this;
    }

    private int lastupdatetime_ ;
    /**
     * <code>int32 lastupdatetime = 13;</code>
     * @return The lastupdatetime.
     */
    @java.lang.Override
    public int getLastupdatetime() {
      return lastupdatetime_;
    }
    /**
     * <code>int32 lastupdatetime = 13;</code>
     * @param value The lastupdatetime to set.
     * @return This builder for chaining.
     */
    public Builder setLastupdatetime(int value) {
      
      lastupdatetime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastupdatetime = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastupdatetime() {
      
      lastupdatetime_ = 0;
      onChanged();
      return this;
    }

    private com.cms.client.network.gpro.DBTaskAttrData taskDatas_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.DBTaskAttrData, com.cms.client.network.gpro.DBTaskAttrData.Builder, com.cms.client.network.gpro.DBTaskAttrDataOrBuilder> taskDatasBuilder_;
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     * @return Whether the taskDatas field is set.
     */
    public boolean hasTaskDatas() {
      return taskDatasBuilder_ != null || taskDatas_ != null;
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     * @return The taskDatas.
     */
    public com.cms.client.network.gpro.DBTaskAttrData getTaskDatas() {
      if (taskDatasBuilder_ == null) {
        return taskDatas_ == null ? com.cms.client.network.gpro.DBTaskAttrData.getDefaultInstance() : taskDatas_;
      } else {
        return taskDatasBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    public Builder setTaskDatas(com.cms.client.network.gpro.DBTaskAttrData value) {
      if (taskDatasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        taskDatas_ = value;
        onChanged();
      } else {
        taskDatasBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    public Builder setTaskDatas(
        com.cms.client.network.gpro.DBTaskAttrData.Builder builderForValue) {
      if (taskDatasBuilder_ == null) {
        taskDatas_ = builderForValue.build();
        onChanged();
      } else {
        taskDatasBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    public Builder mergeTaskDatas(com.cms.client.network.gpro.DBTaskAttrData value) {
      if (taskDatasBuilder_ == null) {
        if (taskDatas_ != null) {
          taskDatas_ =
            com.cms.client.network.gpro.DBTaskAttrData.newBuilder(taskDatas_).mergeFrom(value).buildPartial();
        } else {
          taskDatas_ = value;
        }
        onChanged();
      } else {
        taskDatasBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    public Builder clearTaskDatas() {
      if (taskDatasBuilder_ == null) {
        taskDatas_ = null;
        onChanged();
      } else {
        taskDatas_ = null;
        taskDatasBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    public com.cms.client.network.gpro.DBTaskAttrData.Builder getTaskDatasBuilder() {
      
      onChanged();
      return getTaskDatasFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    public com.cms.client.network.gpro.DBTaskAttrDataOrBuilder getTaskDatasOrBuilder() {
      if (taskDatasBuilder_ != null) {
        return taskDatasBuilder_.getMessageOrBuilder();
      } else {
        return taskDatas_ == null ?
            com.cms.client.network.gpro.DBTaskAttrData.getDefaultInstance() : taskDatas_;
      }
    }
    /**
     * <pre>
     *string task_datas = 14;
     * </pre>
     *
     * <code>.PRO.DBTaskAttrData task_datas = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.DBTaskAttrData, com.cms.client.network.gpro.DBTaskAttrData.Builder, com.cms.client.network.gpro.DBTaskAttrDataOrBuilder> 
        getTaskDatasFieldBuilder() {
      if (taskDatasBuilder_ == null) {
        taskDatasBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cms.client.network.gpro.DBTaskAttrData, com.cms.client.network.gpro.DBTaskAttrData.Builder, com.cms.client.network.gpro.DBTaskAttrDataOrBuilder>(
                getTaskDatas(),
                getParentForChildren(),
                isClean());
        taskDatas_ = null;
      }
      return taskDatasBuilder_;
    }

    private java.lang.Object sourceIid_ = "";
    /**
     * <code>string source_iid = 15;</code>
     * @return The sourceIid.
     */
    public java.lang.String getSourceIid() {
      java.lang.Object ref = sourceIid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceIid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_iid = 15;</code>
     * @return The bytes for sourceIid.
     */
    public com.google.protobuf.ByteString
        getSourceIidBytes() {
      java.lang.Object ref = sourceIid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceIid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_iid = 15;</code>
     * @param value The sourceIid to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceIid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source_iid = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceIid() {
      
      sourceIid_ = getDefaultInstance().getSourceIid();
      onChanged();
      return this;
    }
    /**
     * <code>string source_iid = 15;</code>
     * @param value The bytes for sourceIid to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceIid_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PRO.DBUserTaskItem)
  }

  // @@protoc_insertion_point(class_scope:PRO.DBUserTaskItem)
  private static final com.cms.client.network.gpro.DBUserTaskItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cms.client.network.gpro.DBUserTaskItem();
  }

  public static com.cms.client.network.gpro.DBUserTaskItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DBUserTaskItem>
      PARSER = new com.google.protobuf.AbstractParser<DBUserTaskItem>() {
    @java.lang.Override
    public DBUserTaskItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DBUserTaskItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DBUserTaskItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DBUserTaskItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cms.client.network.gpro.DBUserTaskItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

