// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_internal.proto

package com.cms.client.network.gpro;

public interface DBUserTaskEndItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PRO.DBUserTaskEndItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 ver_ = 1;</code>
   * @return The ver.
   */
  int getVer();

  /**
   * <code>int64 iid = 2;</code>
   * @return The iid.
   */
  long getIid();

  /**
   * <code>int32 task_iid = 4;</code>
   * @return The taskIid.
   */
  int getTaskIid();

  /**
   * <code>int32 qstate = 7;</code>
   * @return The qstate.
   */
  int getQstate();

  /**
   * <code>int32 lastupdatetime = 13;</code>
   * @return The lastupdatetime.
   */
  int getLastupdatetime();
}
