// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eureka_internal.proto

package com.cms.client.network.gpro;

public interface Erk_EurekaBind_ackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PRO.Erk_EurekaBind_ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0:成功 1:token错误 2:暂时不存在该服务
   * </pre>
   *
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
