// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eureka_internal.proto

package com.cms.client.network.gpro;

public final class EurekaInternal {
  private EurekaInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_EurekaServerNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_EurekaServerNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_EurekaBind_req_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_EurekaBind_req_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_EurekaBind_ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_EurekaBind_ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_EurekaUpdate_ntf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_EurekaUpdate_ntf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_Eureka_sync_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_Eureka_sync_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_ServerNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_ServerNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_ServerNode_ExtsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_ServerNode_ExtsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceRegist_req_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceRegist_req_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceRegist_req_ExtsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceRegist_req_ExtsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceRegist_ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceRegist_ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceRegist_Confirm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceRegist_Confirm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceBind_req_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceBind_req_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceBind_ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceBind_ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceSubscribe_req_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceSubscribe_req_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceSubscribe_req_svrinfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceSubscribe_req_svrinfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceSubscribe_ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceSubscribe_ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Erk_ServiceShutdown_ntf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Erk_ServiceShutdown_ntf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Svr_LiveTick_ntf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Svr_LiveTick_ntf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Svr_ServiceBindService_req_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Svr_ServiceBindService_req_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Svr_ServiceBindService_req_MyextsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Svr_ServiceBindService_req_MyextsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PRO_Svr_ServiceBindService_ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PRO_Svr_ServiceBindService_ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025eureka_internal.proto\022\003PRO\"H\n\020EurekaSe" +
      "rverNode\022\013\n\003iid\030\001 \001(\003\022\r\n\005token\030\002 \001(\003\022\n\n\002" +
      "ip\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\"J\n\022Erk_EurekaBind" +
      "_req\022\013\n\003iid\030\001 \001(\003\022\r\n\005token\030\002 \001(\003\022\n\n\002ip\030\003" +
      " \001(\t\022\014\n\004port\030\004 \001(\005\"$\n\022Erk_EurekaBind_ack" +
      "\022\016\n\006result\030\001 \001(\005\"]\n\024Erk_EurekaUpdate_ntf" +
      "\022\r\n\005myiid\030\001 \001(\003\022%\n\006online\030\002 \003(\0132\025.PRO.Eu" +
      "rekaServerNode\022\017\n\007offline\030\003 \003(\003\"0\n\017Erk_E" +
      "ureka_sync\022\r\n\005myiid\030\001 \001(\003\022\016\n\006exists\030\002 \003(" +
      "\003\"\230\001\n\nServerNode\022\013\n\003iid\030\001 \001(\003\022\r\n\005token\030\002" +
      " \001(\003\022\n\n\002ip\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\022\'\n\004exts\030\005" +
      " \003(\0132\031.PRO.ServerNode.ExtsEntry\032+\n\tExtsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\244\001\n" +
      "\025Erk_ServiceRegist_req\022\020\n\010svr_type\030\001 \001(\005" +
      "\022\n\n\002ip\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\0222\n\004exts\030\004 \003(\013" +
      "2$.PRO.Erk_ServiceRegist_req.ExtsEntry\032+" +
      "\n\tExtsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\"\257\001\n\025Erk_ServiceRegist_ack\022\016\n\006result\030" +
      "\001 \001(\005\022\020\n\003iid\030\002 \001(\003H\000\210\001\001\022\022\n\005token\030\003 \001(\003H\001" +
      "\210\001\001\022\026\n\teurekaiid\030\004 \001(\003H\002\210\001\001\022\030\n\013eurekatok" +
      "en\030\005 \001(\003H\003\210\001\001B\006\n\004_iidB\010\n\006_tokenB\014\n\n_eure" +
      "kaiidB\016\n\014_eurekatoken\"7\n\031Erk_ServiceRegi" +
      "st_Confirm\022\013\n\003iid\030\001 \001(\003\022\r\n\005token\030\002 \001(\003\"C" +
      "\n\023Erk_ServiceBind_req\022\020\n\010svr_type\030\001 \001(\005\022" +
      "\013\n\003iid\030\002 \001(\003\022\r\n\005token\030\003 \001(\003\"%\n\023Erk_Servi" +
      "ceBind_ack\022\016\n\006result\030\001 \001(\005\"\277\001\n\030Erk_Servi" +
      "ceSubscribe_req\022\r\n\005myiid\030\001 \001(\003\022\021\n\tmysvrt" +
      "ype\030\002 \001(\005\022\014\n\004myip\030\003 \001(\t\022\016\n\006myport\030\004 \001(\005\022" +
      "7\n\010svr_type\030\005 \003(\0132%.PRO.Erk_ServiceSubsc" +
      "ribe_req.svrinfo\032*\n\007svrinfo\022\020\n\010svr_type\030" +
      "\001 \001(\005\022\r\n\005exits\030\002 \003(\003\"m\n\030Erk_ServiceSubsc" +
      "ribe_ack\022\r\n\005myiid\030\001 \001(\003\022\020\n\010svr_type\030\002 \001(" +
      "\005\022\037\n\006online\030\003 \003(\0132\017.PRO.ServerNode\022\017\n\007of" +
      "fline\030\004 \003(\003\"<\n\027Erk_ServiceShutdown_ntf\022\020" +
      "\n\010svr_type\030\001 \001(\005\022\017\n\007service\030\002 \001(\003\"\022\n\020Svr" +
      "_LiveTick_ntf\"\332\001\n\032Svr_ServiceBindService" +
      "_req\022\020\n\010svr_type\030\001 \001(\005\022\r\n\005myiid\030\002 \001(\003\022\017\n" +
      "\007mytoken\030\003 \001(\003\022;\n\006myexts\030\004 \003(\0132+.PRO.Svr" +
      "_ServiceBindService_req.MyextsEntry\022\r\n\005t" +
      "oiid\030\n \001(\003\022\017\n\007totoken\030\013 \001(\003\032-\n\013MyextsEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"^\n\032Sv" +
      "r_ServiceBindService_ack\022\016\n\006result\030\001 \001(\005" +
      "\022\020\n\010svr_type\030\002 \001(\005\022\r\n\005toiid\030\003 \001(\003\022\017\n\007tot" +
      "oken\030\004 \001(\003*\250\003\n\017ERK_SERVICETYPE\022\024\n\020ERK_SE" +
      "RVICE_NONE\020\000\022\026\n\022ERK_SERVICE_EUREKA\020\001\022\032\n\026" +
      "ERK_SERVICE_DATAROUTER\020\002\022\023\n\017ERK_SERVICE_" +
      "RES\020\003\022\024\n\020ERK_SERVICE_GATE\020\004\022\024\n\020ERK_SERVI" +
      "CE_HOME\020\005\022\025\n\021ERK_SERVICE_LOGIN\020\006\022\031\n\025ERK_" +
      "SERVICE_SVRROUTER\020\007\022\025\n\021ERK_SERVICE_UNION" +
      "\020\010\022\024\n\020ERK_SERVICE_CHAT\020\t\022\024\n\020ERK_SERVICE_" +
      "MAIL\020\n\022\026\n\022ERK_SERVICE_FRIEND\020\013\022\033\n\027ERK_SE" +
      "RVICE_FIGHTROUTER\020\014\022\033\n\027ERK_SERVICE_MATCH" +
      "MAKING\020\r\022\024\n\020ERK_SERVICE_GAME\020\016\022\030\n\024ERK_SE" +
      "RVICE_DATASYNC\020\017\022\023\n\017ERK_SERVICE_MAX\020\020BT\n" +
      "\033com.cms.client.network.gproP\001Z\025gamelib/" +
      "protobuf/gpro\252\002\033com.cms.client.network.g" +
      "prob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PRO_EurekaServerNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PRO_EurekaServerNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_EurekaServerNode_descriptor,
        new java.lang.String[] { "Iid", "Token", "Ip", "Port", });
    internal_static_PRO_Erk_EurekaBind_req_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PRO_Erk_EurekaBind_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_EurekaBind_req_descriptor,
        new java.lang.String[] { "Iid", "Token", "Ip", "Port", });
    internal_static_PRO_Erk_EurekaBind_ack_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PRO_Erk_EurekaBind_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_EurekaBind_ack_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_PRO_Erk_EurekaUpdate_ntf_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PRO_Erk_EurekaUpdate_ntf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_EurekaUpdate_ntf_descriptor,
        new java.lang.String[] { "Myiid", "Online", "Offline", });
    internal_static_PRO_Erk_Eureka_sync_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PRO_Erk_Eureka_sync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_Eureka_sync_descriptor,
        new java.lang.String[] { "Myiid", "Exists", });
    internal_static_PRO_ServerNode_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PRO_ServerNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_ServerNode_descriptor,
        new java.lang.String[] { "Iid", "Token", "Ip", "Port", "Exts", });
    internal_static_PRO_ServerNode_ExtsEntry_descriptor =
      internal_static_PRO_ServerNode_descriptor.getNestedTypes().get(0);
    internal_static_PRO_ServerNode_ExtsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_ServerNode_ExtsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PRO_Erk_ServiceRegist_req_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_PRO_Erk_ServiceRegist_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceRegist_req_descriptor,
        new java.lang.String[] { "SvrType", "Ip", "Port", "Exts", });
    internal_static_PRO_Erk_ServiceRegist_req_ExtsEntry_descriptor =
      internal_static_PRO_Erk_ServiceRegist_req_descriptor.getNestedTypes().get(0);
    internal_static_PRO_Erk_ServiceRegist_req_ExtsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceRegist_req_ExtsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PRO_Erk_ServiceRegist_ack_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_PRO_Erk_ServiceRegist_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceRegist_ack_descriptor,
        new java.lang.String[] { "Result", "Iid", "Token", "Eurekaiid", "Eurekatoken", "Iid", "Token", "Eurekaiid", "Eurekatoken", });
    internal_static_PRO_Erk_ServiceRegist_Confirm_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_PRO_Erk_ServiceRegist_Confirm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceRegist_Confirm_descriptor,
        new java.lang.String[] { "Iid", "Token", });
    internal_static_PRO_Erk_ServiceBind_req_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_PRO_Erk_ServiceBind_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceBind_req_descriptor,
        new java.lang.String[] { "SvrType", "Iid", "Token", });
    internal_static_PRO_Erk_ServiceBind_ack_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_PRO_Erk_ServiceBind_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceBind_ack_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_PRO_Erk_ServiceSubscribe_req_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_PRO_Erk_ServiceSubscribe_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceSubscribe_req_descriptor,
        new java.lang.String[] { "Myiid", "Mysvrtype", "Myip", "Myport", "SvrType", });
    internal_static_PRO_Erk_ServiceSubscribe_req_svrinfo_descriptor =
      internal_static_PRO_Erk_ServiceSubscribe_req_descriptor.getNestedTypes().get(0);
    internal_static_PRO_Erk_ServiceSubscribe_req_svrinfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceSubscribe_req_svrinfo_descriptor,
        new java.lang.String[] { "SvrType", "Exits", });
    internal_static_PRO_Erk_ServiceSubscribe_ack_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_PRO_Erk_ServiceSubscribe_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceSubscribe_ack_descriptor,
        new java.lang.String[] { "Myiid", "SvrType", "Online", "Offline", });
    internal_static_PRO_Erk_ServiceShutdown_ntf_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_PRO_Erk_ServiceShutdown_ntf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Erk_ServiceShutdown_ntf_descriptor,
        new java.lang.String[] { "SvrType", "Service", });
    internal_static_PRO_Svr_LiveTick_ntf_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_PRO_Svr_LiveTick_ntf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Svr_LiveTick_ntf_descriptor,
        new java.lang.String[] { });
    internal_static_PRO_Svr_ServiceBindService_req_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_PRO_Svr_ServiceBindService_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Svr_ServiceBindService_req_descriptor,
        new java.lang.String[] { "SvrType", "Myiid", "Mytoken", "Myexts", "Toiid", "Totoken", });
    internal_static_PRO_Svr_ServiceBindService_req_MyextsEntry_descriptor =
      internal_static_PRO_Svr_ServiceBindService_req_descriptor.getNestedTypes().get(0);
    internal_static_PRO_Svr_ServiceBindService_req_MyextsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Svr_ServiceBindService_req_MyextsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PRO_Svr_ServiceBindService_ack_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_PRO_Svr_ServiceBindService_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PRO_Svr_ServiceBindService_ack_descriptor,
        new java.lang.String[] { "Result", "SvrType", "Toiid", "Totoken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
