// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend_system_internal.proto

package com.cms.client.network.gpro;

/**
 * Protobuf type {@code PRO.Frd_NewFriendOther_ntf}
 */
public final class Frd_NewFriendOther_ntf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PRO.Frd_NewFriendOther_ntf)
    Frd_NewFriendOther_ntfOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Frd_NewFriendOther_ntf.newBuilder() to construct.
  private Frd_NewFriendOther_ntf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Frd_NewFriendOther_ntf() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Frd_NewFriendOther_ntf();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Frd_NewFriendOther_ntf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            notifyRoleiid_ = input.readInt64();
            break;
          }
          case 16: {

            iid_ = input.readInt64();
            break;
          }
          case 26: {
            com.cms.client.network.gpro.FriendRelation.Builder subBuilder = null;
            if (friend_ != null) {
              subBuilder = friend_.toBuilder();
            }
            friend_ = input.readMessage(com.cms.client.network.gpro.FriendRelation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(friend_);
              friend_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cms.client.network.gpro.FriendSystemInternal.internal_static_PRO_Frd_NewFriendOther_ntf_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cms.client.network.gpro.FriendSystemInternal.internal_static_PRO_Frd_NewFriendOther_ntf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cms.client.network.gpro.Frd_NewFriendOther_ntf.class, com.cms.client.network.gpro.Frd_NewFriendOther_ntf.Builder.class);
  }

  public static final int NOTIFY_ROLEIID_FIELD_NUMBER = 1;
  private long notifyRoleiid_;
  /**
   * <code>int64 notify_roleiid = 1;</code>
   * @return The notifyRoleiid.
   */
  @java.lang.Override
  public long getNotifyRoleiid() {
    return notifyRoleiid_;
  }

  public static final int IID_FIELD_NUMBER = 2;
  private long iid_;
  /**
   * <pre>
   *好友关系的编号
   * </pre>
   *
   * <code>int64 iid = 2;</code>
   * @return The iid.
   */
  @java.lang.Override
  public long getIid() {
    return iid_;
  }

  public static final int FRIEND_FIELD_NUMBER = 3;
  private com.cms.client.network.gpro.FriendRelation friend_;
  /**
   * <code>.PRO.FriendRelation friend = 3;</code>
   * @return Whether the friend field is set.
   */
  @java.lang.Override
  public boolean hasFriend() {
    return friend_ != null;
  }
  /**
   * <code>.PRO.FriendRelation friend = 3;</code>
   * @return The friend.
   */
  @java.lang.Override
  public com.cms.client.network.gpro.FriendRelation getFriend() {
    return friend_ == null ? com.cms.client.network.gpro.FriendRelation.getDefaultInstance() : friend_;
  }
  /**
   * <code>.PRO.FriendRelation friend = 3;</code>
   */
  @java.lang.Override
  public com.cms.client.network.gpro.FriendRelationOrBuilder getFriendOrBuilder() {
    return getFriend();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (notifyRoleiid_ != 0L) {
      output.writeInt64(1, notifyRoleiid_);
    }
    if (iid_ != 0L) {
      output.writeInt64(2, iid_);
    }
    if (friend_ != null) {
      output.writeMessage(3, getFriend());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (notifyRoleiid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, notifyRoleiid_);
    }
    if (iid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, iid_);
    }
    if (friend_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFriend());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cms.client.network.gpro.Frd_NewFriendOther_ntf)) {
      return super.equals(obj);
    }
    com.cms.client.network.gpro.Frd_NewFriendOther_ntf other = (com.cms.client.network.gpro.Frd_NewFriendOther_ntf) obj;

    if (getNotifyRoleiid()
        != other.getNotifyRoleiid()) return false;
    if (getIid()
        != other.getIid()) return false;
    if (hasFriend() != other.hasFriend()) return false;
    if (hasFriend()) {
      if (!getFriend()
          .equals(other.getFriend())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NOTIFY_ROLEIID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNotifyRoleiid());
    hash = (37 * hash) + IID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIid());
    if (hasFriend()) {
      hash = (37 * hash) + FRIEND_FIELD_NUMBER;
      hash = (53 * hash) + getFriend().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cms.client.network.gpro.Frd_NewFriendOther_ntf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PRO.Frd_NewFriendOther_ntf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PRO.Frd_NewFriendOther_ntf)
      com.cms.client.network.gpro.Frd_NewFriendOther_ntfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cms.client.network.gpro.FriendSystemInternal.internal_static_PRO_Frd_NewFriendOther_ntf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cms.client.network.gpro.FriendSystemInternal.internal_static_PRO_Frd_NewFriendOther_ntf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cms.client.network.gpro.Frd_NewFriendOther_ntf.class, com.cms.client.network.gpro.Frd_NewFriendOther_ntf.Builder.class);
    }

    // Construct using com.cms.client.network.gpro.Frd_NewFriendOther_ntf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      notifyRoleiid_ = 0L;

      iid_ = 0L;

      if (friendBuilder_ == null) {
        friend_ = null;
      } else {
        friend_ = null;
        friendBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cms.client.network.gpro.FriendSystemInternal.internal_static_PRO_Frd_NewFriendOther_ntf_descriptor;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.Frd_NewFriendOther_ntf getDefaultInstanceForType() {
      return com.cms.client.network.gpro.Frd_NewFriendOther_ntf.getDefaultInstance();
    }

    @java.lang.Override
    public com.cms.client.network.gpro.Frd_NewFriendOther_ntf build() {
      com.cms.client.network.gpro.Frd_NewFriendOther_ntf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.Frd_NewFriendOther_ntf buildPartial() {
      com.cms.client.network.gpro.Frd_NewFriendOther_ntf result = new com.cms.client.network.gpro.Frd_NewFriendOther_ntf(this);
      result.notifyRoleiid_ = notifyRoleiid_;
      result.iid_ = iid_;
      if (friendBuilder_ == null) {
        result.friend_ = friend_;
      } else {
        result.friend_ = friendBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cms.client.network.gpro.Frd_NewFriendOther_ntf) {
        return mergeFrom((com.cms.client.network.gpro.Frd_NewFriendOther_ntf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cms.client.network.gpro.Frd_NewFriendOther_ntf other) {
      if (other == com.cms.client.network.gpro.Frd_NewFriendOther_ntf.getDefaultInstance()) return this;
      if (other.getNotifyRoleiid() != 0L) {
        setNotifyRoleiid(other.getNotifyRoleiid());
      }
      if (other.getIid() != 0L) {
        setIid(other.getIid());
      }
      if (other.hasFriend()) {
        mergeFriend(other.getFriend());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cms.client.network.gpro.Frd_NewFriendOther_ntf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cms.client.network.gpro.Frd_NewFriendOther_ntf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long notifyRoleiid_ ;
    /**
     * <code>int64 notify_roleiid = 1;</code>
     * @return The notifyRoleiid.
     */
    @java.lang.Override
    public long getNotifyRoleiid() {
      return notifyRoleiid_;
    }
    /**
     * <code>int64 notify_roleiid = 1;</code>
     * @param value The notifyRoleiid to set.
     * @return This builder for chaining.
     */
    public Builder setNotifyRoleiid(long value) {
      
      notifyRoleiid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 notify_roleiid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotifyRoleiid() {
      
      notifyRoleiid_ = 0L;
      onChanged();
      return this;
    }

    private long iid_ ;
    /**
     * <pre>
     *好友关系的编号
     * </pre>
     *
     * <code>int64 iid = 2;</code>
     * @return The iid.
     */
    @java.lang.Override
    public long getIid() {
      return iid_;
    }
    /**
     * <pre>
     *好友关系的编号
     * </pre>
     *
     * <code>int64 iid = 2;</code>
     * @param value The iid to set.
     * @return This builder for chaining.
     */
    public Builder setIid(long value) {
      
      iid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *好友关系的编号
     * </pre>
     *
     * <code>int64 iid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIid() {
      
      iid_ = 0L;
      onChanged();
      return this;
    }

    private com.cms.client.network.gpro.FriendRelation friend_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.FriendRelation, com.cms.client.network.gpro.FriendRelation.Builder, com.cms.client.network.gpro.FriendRelationOrBuilder> friendBuilder_;
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     * @return Whether the friend field is set.
     */
    public boolean hasFriend() {
      return friendBuilder_ != null || friend_ != null;
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     * @return The friend.
     */
    public com.cms.client.network.gpro.FriendRelation getFriend() {
      if (friendBuilder_ == null) {
        return friend_ == null ? com.cms.client.network.gpro.FriendRelation.getDefaultInstance() : friend_;
      } else {
        return friendBuilder_.getMessage();
      }
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    public Builder setFriend(com.cms.client.network.gpro.FriendRelation value) {
      if (friendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        friend_ = value;
        onChanged();
      } else {
        friendBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    public Builder setFriend(
        com.cms.client.network.gpro.FriendRelation.Builder builderForValue) {
      if (friendBuilder_ == null) {
        friend_ = builderForValue.build();
        onChanged();
      } else {
        friendBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    public Builder mergeFriend(com.cms.client.network.gpro.FriendRelation value) {
      if (friendBuilder_ == null) {
        if (friend_ != null) {
          friend_ =
            com.cms.client.network.gpro.FriendRelation.newBuilder(friend_).mergeFrom(value).buildPartial();
        } else {
          friend_ = value;
        }
        onChanged();
      } else {
        friendBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    public Builder clearFriend() {
      if (friendBuilder_ == null) {
        friend_ = null;
        onChanged();
      } else {
        friend_ = null;
        friendBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    public com.cms.client.network.gpro.FriendRelation.Builder getFriendBuilder() {
      
      onChanged();
      return getFriendFieldBuilder().getBuilder();
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    public com.cms.client.network.gpro.FriendRelationOrBuilder getFriendOrBuilder() {
      if (friendBuilder_ != null) {
        return friendBuilder_.getMessageOrBuilder();
      } else {
        return friend_ == null ?
            com.cms.client.network.gpro.FriendRelation.getDefaultInstance() : friend_;
      }
    }
    /**
     * <code>.PRO.FriendRelation friend = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.FriendRelation, com.cms.client.network.gpro.FriendRelation.Builder, com.cms.client.network.gpro.FriendRelationOrBuilder> 
        getFriendFieldBuilder() {
      if (friendBuilder_ == null) {
        friendBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cms.client.network.gpro.FriendRelation, com.cms.client.network.gpro.FriendRelation.Builder, com.cms.client.network.gpro.FriendRelationOrBuilder>(
                getFriend(),
                getParentForChildren(),
                isClean());
        friend_ = null;
      }
      return friendBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PRO.Frd_NewFriendOther_ntf)
  }

  // @@protoc_insertion_point(class_scope:PRO.Frd_NewFriendOther_ntf)
  private static final com.cms.client.network.gpro.Frd_NewFriendOther_ntf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cms.client.network.gpro.Frd_NewFriendOther_ntf();
  }

  public static com.cms.client.network.gpro.Frd_NewFriendOther_ntf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Frd_NewFriendOther_ntf>
      PARSER = new com.google.protobuf.AbstractParser<Frd_NewFriendOther_ntf>() {
    @java.lang.Override
    public Frd_NewFriendOther_ntf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Frd_NewFriendOther_ntf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Frd_NewFriendOther_ntf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Frd_NewFriendOther_ntf> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cms.client.network.gpro.Frd_NewFriendOther_ntf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

