// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mail_system.proto

package com.cms.client.network.gpro;

public interface Mail_NewMail_ntfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PRO.Mail_NewMail_ntf)
    com.google.protobuf.MessageOrBuilder {
}
