// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mail_system.proto

package com.cms.client.network.gpro;

public interface Mail_ReadMail_ackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PRO.Mail_ReadMail_ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0:success 1:system error 2:not exist 3:already read
   * </pre>
   *
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();

  /**
   * <code>int64 mail_iid = 2;</code>
   * @return The mailIid.
   */
  long getMailIid();
}
