// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mail_system_internal.proto

package com.cms.client.network.gpro;

/**
 * Protobuf type {@code PRO.Mail_NewMail_ack}
 */
public final class Mail_NewMail_ack extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PRO.Mail_NewMail_ack)
    Mail_NewMail_ackOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mail_NewMail_ack.newBuilder() to construct.
  private Mail_NewMail_ack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mail_NewMail_ack() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mail_NewMail_ack();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Mail_NewMail_ack(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            result_ = input.readInt32();
            break;
          }
          case 18: {
            com.cms.client.network.gpro.MailNormalItem.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = mail_.toBuilder();
            }
            mail_ = input.readMessage(com.cms.client.network.gpro.MailNormalItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mail_);
              mail_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cms.client.network.gpro.MailSystemInternal.internal_static_PRO_Mail_NewMail_ack_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cms.client.network.gpro.MailSystemInternal.internal_static_PRO_Mail_NewMail_ack_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cms.client.network.gpro.Mail_NewMail_ack.class, com.cms.client.network.gpro.Mail_NewMail_ack.Builder.class);
  }

  private int bitField0_;
  public static final int RESULT_FIELD_NUMBER = 1;
  private int result_;
  /**
   * <pre>
   *0:success
   * </pre>
   *
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public int getResult() {
    return result_;
  }

  public static final int MAIL_FIELD_NUMBER = 2;
  private com.cms.client.network.gpro.MailNormalItem mail_;
  /**
   * <code>optional .PRO.MailNormalItem mail = 2;</code>
   * @return Whether the mail field is set.
   */
  @java.lang.Override
  public boolean hasMail() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .PRO.MailNormalItem mail = 2;</code>
   * @return The mail.
   */
  @java.lang.Override
  public com.cms.client.network.gpro.MailNormalItem getMail() {
    return mail_ == null ? com.cms.client.network.gpro.MailNormalItem.getDefaultInstance() : mail_;
  }
  /**
   * <code>optional .PRO.MailNormalItem mail = 2;</code>
   */
  @java.lang.Override
  public com.cms.client.network.gpro.MailNormalItemOrBuilder getMailOrBuilder() {
    return mail_ == null ? com.cms.client.network.gpro.MailNormalItem.getDefaultInstance() : mail_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (result_ != 0) {
      output.writeInt32(1, result_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getMail());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (result_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, result_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMail());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cms.client.network.gpro.Mail_NewMail_ack)) {
      return super.equals(obj);
    }
    com.cms.client.network.gpro.Mail_NewMail_ack other = (com.cms.client.network.gpro.Mail_NewMail_ack) obj;

    if (getResult()
        != other.getResult()) return false;
    if (hasMail() != other.hasMail()) return false;
    if (hasMail()) {
      if (!getMail()
          .equals(other.getMail())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult();
    if (hasMail()) {
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.Mail_NewMail_ack parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cms.client.network.gpro.Mail_NewMail_ack prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PRO.Mail_NewMail_ack}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PRO.Mail_NewMail_ack)
      com.cms.client.network.gpro.Mail_NewMail_ackOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cms.client.network.gpro.MailSystemInternal.internal_static_PRO_Mail_NewMail_ack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cms.client.network.gpro.MailSystemInternal.internal_static_PRO_Mail_NewMail_ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cms.client.network.gpro.Mail_NewMail_ack.class, com.cms.client.network.gpro.Mail_NewMail_ack.Builder.class);
    }

    // Construct using com.cms.client.network.gpro.Mail_NewMail_ack.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMailFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = 0;

      if (mailBuilder_ == null) {
        mail_ = null;
      } else {
        mailBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cms.client.network.gpro.MailSystemInternal.internal_static_PRO_Mail_NewMail_ack_descriptor;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.Mail_NewMail_ack getDefaultInstanceForType() {
      return com.cms.client.network.gpro.Mail_NewMail_ack.getDefaultInstance();
    }

    @java.lang.Override
    public com.cms.client.network.gpro.Mail_NewMail_ack build() {
      com.cms.client.network.gpro.Mail_NewMail_ack result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.Mail_NewMail_ack buildPartial() {
      com.cms.client.network.gpro.Mail_NewMail_ack result = new com.cms.client.network.gpro.Mail_NewMail_ack(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.result_ = result_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (mailBuilder_ == null) {
          result.mail_ = mail_;
        } else {
          result.mail_ = mailBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cms.client.network.gpro.Mail_NewMail_ack) {
        return mergeFrom((com.cms.client.network.gpro.Mail_NewMail_ack)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cms.client.network.gpro.Mail_NewMail_ack other) {
      if (other == com.cms.client.network.gpro.Mail_NewMail_ack.getDefaultInstance()) return this;
      if (other.getResult() != 0) {
        setResult(other.getResult());
      }
      if (other.hasMail()) {
        mergeMail(other.getMail());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cms.client.network.gpro.Mail_NewMail_ack parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cms.client.network.gpro.Mail_NewMail_ack) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int result_ ;
    /**
     * <pre>
     *0:success
     * </pre>
     *
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }
    /**
     * <pre>
     *0:success
     * </pre>
     *
     * <code>int32 result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(int value) {
      
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *0:success
     * </pre>
     *
     * <code>int32 result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = 0;
      onChanged();
      return this;
    }

    private com.cms.client.network.gpro.MailNormalItem mail_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.MailNormalItem, com.cms.client.network.gpro.MailNormalItem.Builder, com.cms.client.network.gpro.MailNormalItemOrBuilder> mailBuilder_;
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     * @return Whether the mail field is set.
     */
    public boolean hasMail() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     * @return The mail.
     */
    public com.cms.client.network.gpro.MailNormalItem getMail() {
      if (mailBuilder_ == null) {
        return mail_ == null ? com.cms.client.network.gpro.MailNormalItem.getDefaultInstance() : mail_;
      } else {
        return mailBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    public Builder setMail(com.cms.client.network.gpro.MailNormalItem value) {
      if (mailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mail_ = value;
        onChanged();
      } else {
        mailBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    public Builder setMail(
        com.cms.client.network.gpro.MailNormalItem.Builder builderForValue) {
      if (mailBuilder_ == null) {
        mail_ = builderForValue.build();
        onChanged();
      } else {
        mailBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    public Builder mergeMail(com.cms.client.network.gpro.MailNormalItem value) {
      if (mailBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            mail_ != null &&
            mail_ != com.cms.client.network.gpro.MailNormalItem.getDefaultInstance()) {
          mail_ =
            com.cms.client.network.gpro.MailNormalItem.newBuilder(mail_).mergeFrom(value).buildPartial();
        } else {
          mail_ = value;
        }
        onChanged();
      } else {
        mailBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    public Builder clearMail() {
      if (mailBuilder_ == null) {
        mail_ = null;
        onChanged();
      } else {
        mailBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    public com.cms.client.network.gpro.MailNormalItem.Builder getMailBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMailFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    public com.cms.client.network.gpro.MailNormalItemOrBuilder getMailOrBuilder() {
      if (mailBuilder_ != null) {
        return mailBuilder_.getMessageOrBuilder();
      } else {
        return mail_ == null ?
            com.cms.client.network.gpro.MailNormalItem.getDefaultInstance() : mail_;
      }
    }
    /**
     * <code>optional .PRO.MailNormalItem mail = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.MailNormalItem, com.cms.client.network.gpro.MailNormalItem.Builder, com.cms.client.network.gpro.MailNormalItemOrBuilder> 
        getMailFieldBuilder() {
      if (mailBuilder_ == null) {
        mailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cms.client.network.gpro.MailNormalItem, com.cms.client.network.gpro.MailNormalItem.Builder, com.cms.client.network.gpro.MailNormalItemOrBuilder>(
                getMail(),
                getParentForChildren(),
                isClean());
        mail_ = null;
      }
      return mailBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PRO.Mail_NewMail_ack)
  }

  // @@protoc_insertion_point(class_scope:PRO.Mail_NewMail_ack)
  private static final com.cms.client.network.gpro.Mail_NewMail_ack DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cms.client.network.gpro.Mail_NewMail_ack();
  }

  public static com.cms.client.network.gpro.Mail_NewMail_ack getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mail_NewMail_ack>
      PARSER = new com.google.protobuf.AbstractParser<Mail_NewMail_ack>() {
    @java.lang.Override
    public Mail_NewMail_ack parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Mail_NewMail_ack(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Mail_NewMail_ack> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mail_NewMail_ack> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cms.client.network.gpro.Mail_NewMail_ack getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

