// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_system.proto

package com.cms.client.network.gpro;

public interface Task_ObtainReward_ntfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PRO.Task_ObtainReward_ntf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 task_iid = 1;</code>
   * @return The taskIid.
   */
  int getTaskIid();

  /**
   * <code>.PRO.TaskRewardItems reward = 2;</code>
   * @return Whether the reward field is set.
   */
  boolean hasReward();
  /**
   * <code>.PRO.TaskRewardItems reward = 2;</code>
   * @return The reward.
   */
  com.cms.client.network.gpro.TaskRewardItems getReward();
  /**
   * <code>.PRO.TaskRewardItems reward = 2;</code>
   */
  com.cms.client.network.gpro.TaskRewardItemsOrBuilder getRewardOrBuilder();
}
