// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_system.proto

package com.cms.client.network.gpro;

public interface Task_GiveupTask_reqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PRO.Task_GiveupTask_req)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *放弃的任务iid
   * </pre>
   *
   * <code>int32 task_iid = 1;</code>
   * @return The taskIid.
   */
  int getTaskIid();
}
