// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_login.proto

package com.cms.client.network.gpro;

/**
 * <pre>
 *role detail info
 * </pre>
 *
 * Protobuf type {@code PRO.User_RoleDetailA_ntf}
 */
public final class User_RoleDetailA_ntf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PRO.User_RoleDetailA_ntf)
    User_RoleDetailA_ntfOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User_RoleDetailA_ntf.newBuilder() to construct.
  private User_RoleDetailA_ntf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User_RoleDetailA_ntf() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User_RoleDetailA_ntf();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User_RoleDetailA_ntf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.cms.client.network.gpro.UserToken.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = utoken_.toBuilder();
            }
            utoken_ = input.readMessage(com.cms.client.network.gpro.UserToken.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(utoken_);
              utoken_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.cms.client.network.gpro.DBUserHome.Builder subBuilder = null;
            if (home_ != null) {
              subBuilder = home_.toBuilder();
            }
            home_ = input.readMessage(com.cms.client.network.gpro.DBUserHome.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(home_);
              home_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.cms.client.network.gpro.DBUserHomeStructure.Builder subBuilder = null;
            if (homeitems_ != null) {
              subBuilder = homeitems_.toBuilder();
            }
            homeitems_ = input.readMessage(com.cms.client.network.gpro.DBUserHomeStructure.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(homeitems_);
              homeitems_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cms.client.network.gpro.UserLogin.internal_static_PRO_User_RoleDetailA_ntf_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cms.client.network.gpro.UserLogin.internal_static_PRO_User_RoleDetailA_ntf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cms.client.network.gpro.User_RoleDetailA_ntf.class, com.cms.client.network.gpro.User_RoleDetailA_ntf.Builder.class);
  }

  private int bitField0_;
  public static final int UTOKEN_FIELD_NUMBER = 1;
  private com.cms.client.network.gpro.UserToken utoken_;
  /**
   * <code>optional .PRO.UserToken utoken = 1;</code>
   * @return Whether the utoken field is set.
   */
  @java.lang.Override
  public boolean hasUtoken() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .PRO.UserToken utoken = 1;</code>
   * @return The utoken.
   */
  @java.lang.Override
  public com.cms.client.network.gpro.UserToken getUtoken() {
    return utoken_ == null ? com.cms.client.network.gpro.UserToken.getDefaultInstance() : utoken_;
  }
  /**
   * <code>optional .PRO.UserToken utoken = 1;</code>
   */
  @java.lang.Override
  public com.cms.client.network.gpro.UserTokenOrBuilder getUtokenOrBuilder() {
    return utoken_ == null ? com.cms.client.network.gpro.UserToken.getDefaultInstance() : utoken_;
  }

  public static final int HOME_FIELD_NUMBER = 2;
  private com.cms.client.network.gpro.DBUserHome home_;
  /**
   * <code>.PRO.DBUserHome home = 2;</code>
   * @return Whether the home field is set.
   */
  @java.lang.Override
  public boolean hasHome() {
    return home_ != null;
  }
  /**
   * <code>.PRO.DBUserHome home = 2;</code>
   * @return The home.
   */
  @java.lang.Override
  public com.cms.client.network.gpro.DBUserHome getHome() {
    return home_ == null ? com.cms.client.network.gpro.DBUserHome.getDefaultInstance() : home_;
  }
  /**
   * <code>.PRO.DBUserHome home = 2;</code>
   */
  @java.lang.Override
  public com.cms.client.network.gpro.DBUserHomeOrBuilder getHomeOrBuilder() {
    return getHome();
  }

  public static final int HOMEITEMS_FIELD_NUMBER = 3;
  private com.cms.client.network.gpro.DBUserHomeStructure homeitems_;
  /**
   * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
   * @return Whether the homeitems field is set.
   */
  @java.lang.Override
  public boolean hasHomeitems() {
    return homeitems_ != null;
  }
  /**
   * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
   * @return The homeitems.
   */
  @java.lang.Override
  public com.cms.client.network.gpro.DBUserHomeStructure getHomeitems() {
    return homeitems_ == null ? com.cms.client.network.gpro.DBUserHomeStructure.getDefaultInstance() : homeitems_;
  }
  /**
   * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
   */
  @java.lang.Override
  public com.cms.client.network.gpro.DBUserHomeStructureOrBuilder getHomeitemsOrBuilder() {
    return getHomeitems();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getUtoken());
    }
    if (home_ != null) {
      output.writeMessage(2, getHome());
    }
    if (homeitems_ != null) {
      output.writeMessage(3, getHomeitems());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUtoken());
    }
    if (home_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHome());
    }
    if (homeitems_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getHomeitems());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cms.client.network.gpro.User_RoleDetailA_ntf)) {
      return super.equals(obj);
    }
    com.cms.client.network.gpro.User_RoleDetailA_ntf other = (com.cms.client.network.gpro.User_RoleDetailA_ntf) obj;

    if (hasUtoken() != other.hasUtoken()) return false;
    if (hasUtoken()) {
      if (!getUtoken()
          .equals(other.getUtoken())) return false;
    }
    if (hasHome() != other.hasHome()) return false;
    if (hasHome()) {
      if (!getHome()
          .equals(other.getHome())) return false;
    }
    if (hasHomeitems() != other.hasHomeitems()) return false;
    if (hasHomeitems()) {
      if (!getHomeitems()
          .equals(other.getHomeitems())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUtoken()) {
      hash = (37 * hash) + UTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getUtoken().hashCode();
    }
    if (hasHome()) {
      hash = (37 * hash) + HOME_FIELD_NUMBER;
      hash = (53 * hash) + getHome().hashCode();
    }
    if (hasHomeitems()) {
      hash = (37 * hash) + HOMEITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getHomeitems().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cms.client.network.gpro.User_RoleDetailA_ntf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cms.client.network.gpro.User_RoleDetailA_ntf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *role detail info
   * </pre>
   *
   * Protobuf type {@code PRO.User_RoleDetailA_ntf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PRO.User_RoleDetailA_ntf)
      com.cms.client.network.gpro.User_RoleDetailA_ntfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cms.client.network.gpro.UserLogin.internal_static_PRO_User_RoleDetailA_ntf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cms.client.network.gpro.UserLogin.internal_static_PRO_User_RoleDetailA_ntf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cms.client.network.gpro.User_RoleDetailA_ntf.class, com.cms.client.network.gpro.User_RoleDetailA_ntf.Builder.class);
    }

    // Construct using com.cms.client.network.gpro.User_RoleDetailA_ntf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUtokenFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (utokenBuilder_ == null) {
        utoken_ = null;
      } else {
        utokenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (homeBuilder_ == null) {
        home_ = null;
      } else {
        home_ = null;
        homeBuilder_ = null;
      }
      if (homeitemsBuilder_ == null) {
        homeitems_ = null;
      } else {
        homeitems_ = null;
        homeitemsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cms.client.network.gpro.UserLogin.internal_static_PRO_User_RoleDetailA_ntf_descriptor;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.User_RoleDetailA_ntf getDefaultInstanceForType() {
      return com.cms.client.network.gpro.User_RoleDetailA_ntf.getDefaultInstance();
    }

    @java.lang.Override
    public com.cms.client.network.gpro.User_RoleDetailA_ntf build() {
      com.cms.client.network.gpro.User_RoleDetailA_ntf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cms.client.network.gpro.User_RoleDetailA_ntf buildPartial() {
      com.cms.client.network.gpro.User_RoleDetailA_ntf result = new com.cms.client.network.gpro.User_RoleDetailA_ntf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (utokenBuilder_ == null) {
          result.utoken_ = utoken_;
        } else {
          result.utoken_ = utokenBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (homeBuilder_ == null) {
        result.home_ = home_;
      } else {
        result.home_ = homeBuilder_.build();
      }
      if (homeitemsBuilder_ == null) {
        result.homeitems_ = homeitems_;
      } else {
        result.homeitems_ = homeitemsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cms.client.network.gpro.User_RoleDetailA_ntf) {
        return mergeFrom((com.cms.client.network.gpro.User_RoleDetailA_ntf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cms.client.network.gpro.User_RoleDetailA_ntf other) {
      if (other == com.cms.client.network.gpro.User_RoleDetailA_ntf.getDefaultInstance()) return this;
      if (other.hasUtoken()) {
        mergeUtoken(other.getUtoken());
      }
      if (other.hasHome()) {
        mergeHome(other.getHome());
      }
      if (other.hasHomeitems()) {
        mergeHomeitems(other.getHomeitems());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cms.client.network.gpro.User_RoleDetailA_ntf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cms.client.network.gpro.User_RoleDetailA_ntf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.cms.client.network.gpro.UserToken utoken_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.UserToken, com.cms.client.network.gpro.UserToken.Builder, com.cms.client.network.gpro.UserTokenOrBuilder> utokenBuilder_;
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     * @return Whether the utoken field is set.
     */
    public boolean hasUtoken() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     * @return The utoken.
     */
    public com.cms.client.network.gpro.UserToken getUtoken() {
      if (utokenBuilder_ == null) {
        return utoken_ == null ? com.cms.client.network.gpro.UserToken.getDefaultInstance() : utoken_;
      } else {
        return utokenBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    public Builder setUtoken(com.cms.client.network.gpro.UserToken value) {
      if (utokenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        utoken_ = value;
        onChanged();
      } else {
        utokenBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    public Builder setUtoken(
        com.cms.client.network.gpro.UserToken.Builder builderForValue) {
      if (utokenBuilder_ == null) {
        utoken_ = builderForValue.build();
        onChanged();
      } else {
        utokenBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    public Builder mergeUtoken(com.cms.client.network.gpro.UserToken value) {
      if (utokenBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            utoken_ != null &&
            utoken_ != com.cms.client.network.gpro.UserToken.getDefaultInstance()) {
          utoken_ =
            com.cms.client.network.gpro.UserToken.newBuilder(utoken_).mergeFrom(value).buildPartial();
        } else {
          utoken_ = value;
        }
        onChanged();
      } else {
        utokenBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    public Builder clearUtoken() {
      if (utokenBuilder_ == null) {
        utoken_ = null;
        onChanged();
      } else {
        utokenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    public com.cms.client.network.gpro.UserToken.Builder getUtokenBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getUtokenFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    public com.cms.client.network.gpro.UserTokenOrBuilder getUtokenOrBuilder() {
      if (utokenBuilder_ != null) {
        return utokenBuilder_.getMessageOrBuilder();
      } else {
        return utoken_ == null ?
            com.cms.client.network.gpro.UserToken.getDefaultInstance() : utoken_;
      }
    }
    /**
     * <code>optional .PRO.UserToken utoken = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.UserToken, com.cms.client.network.gpro.UserToken.Builder, com.cms.client.network.gpro.UserTokenOrBuilder> 
        getUtokenFieldBuilder() {
      if (utokenBuilder_ == null) {
        utokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cms.client.network.gpro.UserToken, com.cms.client.network.gpro.UserToken.Builder, com.cms.client.network.gpro.UserTokenOrBuilder>(
                getUtoken(),
                getParentForChildren(),
                isClean());
        utoken_ = null;
      }
      return utokenBuilder_;
    }

    private com.cms.client.network.gpro.DBUserHome home_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.DBUserHome, com.cms.client.network.gpro.DBUserHome.Builder, com.cms.client.network.gpro.DBUserHomeOrBuilder> homeBuilder_;
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     * @return Whether the home field is set.
     */
    public boolean hasHome() {
      return homeBuilder_ != null || home_ != null;
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     * @return The home.
     */
    public com.cms.client.network.gpro.DBUserHome getHome() {
      if (homeBuilder_ == null) {
        return home_ == null ? com.cms.client.network.gpro.DBUserHome.getDefaultInstance() : home_;
      } else {
        return homeBuilder_.getMessage();
      }
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    public Builder setHome(com.cms.client.network.gpro.DBUserHome value) {
      if (homeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        home_ = value;
        onChanged();
      } else {
        homeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    public Builder setHome(
        com.cms.client.network.gpro.DBUserHome.Builder builderForValue) {
      if (homeBuilder_ == null) {
        home_ = builderForValue.build();
        onChanged();
      } else {
        homeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    public Builder mergeHome(com.cms.client.network.gpro.DBUserHome value) {
      if (homeBuilder_ == null) {
        if (home_ != null) {
          home_ =
            com.cms.client.network.gpro.DBUserHome.newBuilder(home_).mergeFrom(value).buildPartial();
        } else {
          home_ = value;
        }
        onChanged();
      } else {
        homeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    public Builder clearHome() {
      if (homeBuilder_ == null) {
        home_ = null;
        onChanged();
      } else {
        home_ = null;
        homeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    public com.cms.client.network.gpro.DBUserHome.Builder getHomeBuilder() {
      
      onChanged();
      return getHomeFieldBuilder().getBuilder();
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    public com.cms.client.network.gpro.DBUserHomeOrBuilder getHomeOrBuilder() {
      if (homeBuilder_ != null) {
        return homeBuilder_.getMessageOrBuilder();
      } else {
        return home_ == null ?
            com.cms.client.network.gpro.DBUserHome.getDefaultInstance() : home_;
      }
    }
    /**
     * <code>.PRO.DBUserHome home = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.DBUserHome, com.cms.client.network.gpro.DBUserHome.Builder, com.cms.client.network.gpro.DBUserHomeOrBuilder> 
        getHomeFieldBuilder() {
      if (homeBuilder_ == null) {
        homeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cms.client.network.gpro.DBUserHome, com.cms.client.network.gpro.DBUserHome.Builder, com.cms.client.network.gpro.DBUserHomeOrBuilder>(
                getHome(),
                getParentForChildren(),
                isClean());
        home_ = null;
      }
      return homeBuilder_;
    }

    private com.cms.client.network.gpro.DBUserHomeStructure homeitems_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.DBUserHomeStructure, com.cms.client.network.gpro.DBUserHomeStructure.Builder, com.cms.client.network.gpro.DBUserHomeStructureOrBuilder> homeitemsBuilder_;
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     * @return Whether the homeitems field is set.
     */
    public boolean hasHomeitems() {
      return homeitemsBuilder_ != null || homeitems_ != null;
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     * @return The homeitems.
     */
    public com.cms.client.network.gpro.DBUserHomeStructure getHomeitems() {
      if (homeitemsBuilder_ == null) {
        return homeitems_ == null ? com.cms.client.network.gpro.DBUserHomeStructure.getDefaultInstance() : homeitems_;
      } else {
        return homeitemsBuilder_.getMessage();
      }
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    public Builder setHomeitems(com.cms.client.network.gpro.DBUserHomeStructure value) {
      if (homeitemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        homeitems_ = value;
        onChanged();
      } else {
        homeitemsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    public Builder setHomeitems(
        com.cms.client.network.gpro.DBUserHomeStructure.Builder builderForValue) {
      if (homeitemsBuilder_ == null) {
        homeitems_ = builderForValue.build();
        onChanged();
      } else {
        homeitemsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    public Builder mergeHomeitems(com.cms.client.network.gpro.DBUserHomeStructure value) {
      if (homeitemsBuilder_ == null) {
        if (homeitems_ != null) {
          homeitems_ =
            com.cms.client.network.gpro.DBUserHomeStructure.newBuilder(homeitems_).mergeFrom(value).buildPartial();
        } else {
          homeitems_ = value;
        }
        onChanged();
      } else {
        homeitemsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    public Builder clearHomeitems() {
      if (homeitemsBuilder_ == null) {
        homeitems_ = null;
        onChanged();
      } else {
        homeitems_ = null;
        homeitemsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    public com.cms.client.network.gpro.DBUserHomeStructure.Builder getHomeitemsBuilder() {
      
      onChanged();
      return getHomeitemsFieldBuilder().getBuilder();
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    public com.cms.client.network.gpro.DBUserHomeStructureOrBuilder getHomeitemsOrBuilder() {
      if (homeitemsBuilder_ != null) {
        return homeitemsBuilder_.getMessageOrBuilder();
      } else {
        return homeitems_ == null ?
            com.cms.client.network.gpro.DBUserHomeStructure.getDefaultInstance() : homeitems_;
      }
    }
    /**
     * <code>.PRO.DBUserHomeStructure homeitems = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cms.client.network.gpro.DBUserHomeStructure, com.cms.client.network.gpro.DBUserHomeStructure.Builder, com.cms.client.network.gpro.DBUserHomeStructureOrBuilder> 
        getHomeitemsFieldBuilder() {
      if (homeitemsBuilder_ == null) {
        homeitemsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cms.client.network.gpro.DBUserHomeStructure, com.cms.client.network.gpro.DBUserHomeStructure.Builder, com.cms.client.network.gpro.DBUserHomeStructureOrBuilder>(
                getHomeitems(),
                getParentForChildren(),
                isClean());
        homeitems_ = null;
      }
      return homeitemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PRO.User_RoleDetailA_ntf)
  }

  // @@protoc_insertion_point(class_scope:PRO.User_RoleDetailA_ntf)
  private static final com.cms.client.network.gpro.User_RoleDetailA_ntf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cms.client.network.gpro.User_RoleDetailA_ntf();
  }

  public static com.cms.client.network.gpro.User_RoleDetailA_ntf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User_RoleDetailA_ntf>
      PARSER = new com.google.protobuf.AbstractParser<User_RoleDetailA_ntf>() {
    @java.lang.Override
    public User_RoleDetailA_ntf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User_RoleDetailA_ntf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User_RoleDetailA_ntf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User_RoleDetailA_ntf> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cms.client.network.gpro.User_RoleDetailA_ntf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

